export default function FiveRDetailsSlide() {
  return (
    <div className="relative w-screen h-screen overflow-hidden bg-gradient-to-br from-[#1A0D40] to-[#251560]">
      <div className="absolute right-0 top-0 w-[40vw] h-full bg-gradient-to-l from-[#D4A843]/3 to-transparent" />

      <div className="relative flex h-full px-[7vw] py-[7vh]">
        <div className="w-[45%] flex flex-col justify-center pr-[3vw]">
          <p className="font-body text-[1.5vw] tracking-[0.2em] text-[#D4A843] uppercase mb-[2vh]">
            Protocol Architecture
          </p>
          <h2 className="font-display text-[3.2vw] leading-[1.1] text-[#F5F0E8] mb-[3vh]">
            How the 5R Model Works in Practice
          </h2>
          <p className="font-body text-[1.5vw] text-[#B8A4E0]/65 leading-relaxed">
            Every patient receives a personalized protocol generated by DR. FORMULA, our AI Protocol Architect. The system analyzes patient history, diagnostics, and goals to sequence the 5R phases with specific products, dosages, and timelines.
          </p>
        </div>

        <div className="w-[55%] flex flex-col justify-center gap-[2vh] pl-[2vw]">
          <div className="flex gap-[1.5vw] items-start">
            <div className="w-[2.5vw] h-[2.5vw] rounded-full bg-[#D4A843]/20 flex items-center justify-center shrink-0 mt-[0.3vh]">
              <span className="font-body text-[1.2vw] font-bold text-[#D4A843]">1</span>
            </div>
            <div>
              <h4 className="font-body text-[1.5vw] font-bold text-[#F5F0E8]">Patient Intake & Diagnostics</h4>
              <p className="font-body text-[1.3vw] text-[#B8A4E0]/60 mt-[0.5vh]">Comprehensive history, blood analysis, ECS profiling, and symptom mapping</p>
            </div>
          </div>

          <div className="flex gap-[1.5vw] items-start">
            <div className="w-[2.5vw] h-[2.5vw] rounded-full bg-[#D4A843]/20 flex items-center justify-center shrink-0 mt-[0.3vh]">
              <span className="font-body text-[1.2vw] font-bold text-[#D4A843]">2</span>
            </div>
            <div>
              <h4 className="font-body text-[1.5vw] font-bold text-[#F5F0E8]">AI Root Cause Analysis</h4>
              <p className="font-body text-[1.3vw] text-[#B8A4E0]/60 mt-[0.5vh]">DR. FORMULA identifies ranked root causes across toxicity, deficiency, and dysregulation</p>
            </div>
          </div>

          <div className="flex gap-[1.5vw] items-start">
            <div className="w-[2.5vw] h-[2.5vw] rounded-full bg-[#D4A843]/20 flex items-center justify-center shrink-0 mt-[0.3vh]">
              <span className="font-body text-[1.2vw] font-bold text-[#D4A843]">3</span>
            </div>
            <div>
              <h4 className="font-body text-[1.5vw] font-bold text-[#F5F0E8]">Protocol Generation</h4>
              <p className="font-body text-[1.3vw] text-[#B8A4E0]/60 mt-[0.5vh]">Complete treatment plan: peptides, supplements, IV therapy, detox, and daily schedule</p>
            </div>
          </div>

          <div className="flex gap-[1.5vw] items-start">
            <div className="w-[2.5vw] h-[2.5vw] rounded-full bg-[#D4A843]/20 flex items-center justify-center shrink-0 mt-[0.3vh]">
              <span className="font-body text-[1.2vw] font-bold text-[#D4A843]">4</span>
            </div>
            <div>
              <h4 className="font-body text-[1.5vw] font-bold text-[#F5F0E8]">Trustee Review & Delivery</h4>
              <p className="font-body text-[1.3vw] text-[#B8A4E0]/60 mt-[0.5vh]">Human review by the Trustee, refinement, PDF generation, and member delivery</p>
            </div>
          </div>

          <div className="flex gap-[1.5vw] items-start">
            <div className="w-[2.5vw] h-[2.5vw] rounded-full bg-[#D4A843]/20 flex items-center justify-center shrink-0 mt-[0.3vh]">
              <span className="font-body text-[1.2vw] font-bold text-[#D4A843]">5</span>
            </div>
            <div>
              <h4 className="font-body text-[1.5vw] font-bold text-[#F5F0E8]">Follow-Up & Adaptation</h4>
              <p className="font-body text-[1.3vw] text-[#B8A4E0]/60 mt-[0.5vh]">Scheduled follow-ups, lab retesting, and protocol adjustments based on progress</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
