import { sendEmail } from './gmail';

const FFPMA_BRAND = {
  primaryColor: '#0891b2',
  accentColor: '#d97706',
  logoUrl: 'https://www.forgottenformula.com/wp-content/uploads/2024/01/ff-logo.png',
  siteUrl: 'https://www.forgottenformula.com',
  fromName: 'Forgotten Formula PMA',
};

function wrapInBrandedTemplate(title: string, bodyHtml: string, preheader?: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${title}</title>
<style>
  body { margin: 0; padding: 0; font-family: 'Segoe UI', Arial, Helvetica, sans-serif; background: #0a0a0f; color: #e2e8f0; }
  .wrapper { max-width: 600px; margin: 0 auto; }
  .header { background: linear-gradient(135deg, #0891b2, #0e7490); padding: 32px 24px; text-align: center; border-radius: 12px 12px 0 0; }
  .header h1 { color: #fff; margin: 0; font-size: 24px; font-weight: 700; }
  .header p { color: rgba(255,255,255,0.85); margin: 8px 0 0; font-size: 14px; }
  .content { background: #111827; padding: 32px 24px; border-left: 1px solid #1e293b; border-right: 1px solid #1e293b; }
  .content p { line-height: 1.7; color: #cbd5e1; margin: 0 0 16px; }
  .content h2 { color: #22d3ee; font-size: 20px; margin: 24px 0 12px; }
  .content h3 { color: #fbbf24; font-size: 16px; margin: 20px 0 8px; }
  .highlight { background: #1e293b; border-left: 4px solid #0891b2; padding: 16px; margin: 16px 0; border-radius: 0 8px 8px 0; }
  .cta-button { display: inline-block; background: linear-gradient(135deg, #d97706, #b45309); color: #fff; padding: 14px 32px; border-radius: 8px; text-decoration: none; font-weight: 700; font-size: 16px; margin: 16px 0; }
  .footer { background: #030712; padding: 24px; text-align: center; border-radius: 0 0 12px 12px; border: 1px solid #1e293b; border-top: none; }
  .footer p { color: #64748b; font-size: 12px; margin: 4px 0; }
  .footer a { color: #0891b2; text-decoration: none; }
  .divider { border: none; border-top: 1px solid #1e293b; margin: 24px 0; }
  ul { padding-left: 20px; }
  li { color: #cbd5e1; margin: 8px 0; line-height: 1.6; }
</style>
</head>
<body>
${preheader ? `<div style="display:none;max-height:0;overflow:hidden;">${preheader}</div>` : ''}
<div class="wrapper">
  <div class="header">
    <h1>${title}</h1>
    <p>Forgotten Formula PMA &bull; Private Member Association</p>
  </div>
  <div class="content">
    ${bodyHtml}
  </div>
  <div class="footer">
    <p><strong>Forgotten Formula PMA</strong></p>
    <p>Private Member Association &bull; Justin, TX 76247</p>
    <p style="margin-top: 12px;">
      <a href="${FFPMA_BRAND.siteUrl}/privacy-policy">Privacy Policy</a> &bull;
      <a href="${FFPMA_BRAND.siteUrl}/terms">Terms of Service</a> &bull;
      <a href="${FFPMA_BRAND.siteUrl}/pma-agreement">PMA Agreement</a>
    </p>
    <p style="margin-top: 8px; color: #475569;">This communication is for PMA members only.</p>
  </div>
</div>
</body>
</html>`;
}

export const EMAIL_TEMPLATES = {
  welcomeOnboarding(memberName: string): { subject: string; html: string } {
    const subject = 'Welcome to Forgotten Formula PMA - Your Healing Journey Begins';
    const html = wrapInBrandedTemplate(
      'Welcome to the Family',
      `
      <p>Dear ${memberName},</p>
      <p>Welcome to Forgotten Formula PMA. You have joined a community dedicated to <strong>healing over profits</strong> and <strong>nature over synthetic</strong>.</p>

      <div class="highlight">
        <strong>What happens next:</strong>
        <ol>
          <li>Complete your <strong>Member Intake Form</strong> so our doctors can understand your health goals</li>
          <li>Your personalized <strong>Healing Protocol</strong> will be generated by our AI-powered system</li>
          <li>Browse our <strong>Product Catalog</strong> for CGMP-manufactured therapeutics</li>
          <li>Schedule your first consultation with a network physician</li>
        </ol>
      </div>

      <h2>Your AI Support Team</h2>
      <p>As a member, you have access to specialized AI agents available 24/7:</p>
      <ul>
        <li><strong>DIANE</strong> - Nutrition &amp; dietary guidance</li>
        <li><strong>PETE</strong> - Peptide protocol specialist</li>
        <li><strong>DR-TRIAGE</strong> - Health assessment and routing</li>
        <li><strong>PAT</strong> - Product recommendations</li>
      </ul>

      <p style="text-align: center;">
        <a href="${FFPMA_BRAND.siteUrl}/member" class="cta-button">Access Your Member Dashboard</a>
      </p>

      <hr class="divider">
      <p style="font-style: italic; color: #94a3b8;">"The Forgotten Formula remembers what modern medicine forgot - that the body knows the way."</p>
      `,
      'Welcome to Forgotten Formula PMA - your healing journey starts now'
    );
    return { subject, html };
  },

  intakeConfirmation(memberName: string, intakeId: number): { subject: string; html: string } {
    const subject = 'Intake Form Received - Protocol Generation in Progress';
    const html = wrapInBrandedTemplate(
      'Intake Form Confirmed',
      `
      <p>Dear ${memberName},</p>
      <p>We have received your completed Member Intake Form (ID: #${intakeId}). Thank you for taking this important step in your healing journey.</p>

      <div class="highlight">
        <strong>What happens now:</strong>
        <p>Our AI-powered Protocol Assembly system is analyzing your health information to create a personalized healing protocol. This typically takes 24-48 hours.</p>
      </div>

      <h3>Your protocol will include:</h3>
      <ul>
        <li>Personalized supplement recommendations</li>
        <li>Dietary guidance based on your specific conditions</li>
        <li>Detoxification strategy tailored to your needs</li>
        <li>Product recommendations from our catalog</li>
      </ul>

      <p>You will receive a notification when your protocol is ready for review.</p>

      <p style="text-align: center;">
        <a href="${FFPMA_BRAND.siteUrl}/member" class="cta-button">View Your Dashboard</a>
      </p>
      `,
      'Your intake form has been received and your protocol is being generated'
    );
    return { subject, html };
  },

  protocolDelivery(memberName: string, protocolId: number, slidesUrl?: string): { subject: string; html: string } {
    const subject = 'Your Personalized Healing Protocol is Ready';
    const html = wrapInBrandedTemplate(
      'Your Protocol is Ready',
      `
      <p>Dear ${memberName},</p>
      <p>Your personalized healing protocol has been generated and is ready for review.</p>

      <div class="highlight">
        <strong>Protocol ID:</strong> #${protocolId}<br>
        ${slidesUrl ? `<strong>View Slides:</strong> <a href="${slidesUrl}" style="color: #22d3ee;">Open Presentation</a>` : ''}
      </div>

      <h2>Next Steps</h2>
      <ol>
        <li><strong>Review</strong> your protocol on the member dashboard</li>
        <li><strong>Schedule</strong> a consultation to discuss with your doctor</li>
        <li><strong>Order</strong> recommended products from the catalog</li>
        <li><strong>Begin</strong> your personalized healing journey</li>
      </ol>

      <p>If you have questions about your protocol, our AI support team is available around the clock through your member dashboard.</p>

      <p style="text-align: center;">
        <a href="${FFPMA_BRAND.siteUrl}/member" class="cta-button">View Your Protocol</a>
      </p>
      `,
      'Your personalized healing protocol has been generated and is ready for review'
    );
    return { subject, html };
  },

  launchAnnouncement(): { subject: string; html: string } {
    const subject = 'ALLIO v1 Launches April 1, 2026 - The Future of Healing is Here';
    const html = wrapInBrandedTemplate(
      'ALLIO v1 Launch - April 1, 2026',
      `
      <p>Dear Member,</p>
      <p>We are thrilled to announce that <strong>ALLIO v1</strong>, our complete AI-powered healing ecosystem, officially launches on <strong>April 1, 2026</strong>.</p>

      <div class="highlight">
        <h3 style="margin-top: 0;">What is ALLIO?</h3>
        <p style="margin-bottom: 0;">ALLIO is a unified healing intelligence - a network of 48 specialized AI agents working alongside human doctors and practitioners. Neither male nor female, but whole. A warrior who fights with truth. A healer who addresses root causes.</p>
      </div>

      <h2>Launch Day Features</h2>
      <ul>
        <li><strong>AI-Powered Protocol Generation</strong> - Personalized healing plans from intake to protocol</li>
        <li><strong>320+ Healing Products</strong> - CGMP-manufactured supplements, peptides, and therapeutics</li>
        <li><strong>Live Blood Analysis AI</strong> - Darkfield microscopy with AI-assisted interpretation</li>
        <li><strong>48 Specialized AI Agents</strong> - Research, nutrition, peptides, legal, and more</li>
        <li><strong>Doctor Network</strong> - Root cause physicians across the country</li>
        <li><strong>Frequency Medicine</strong> - Rife, PEMF, and bio-resonance protocols</li>
      </ul>

      <h2>The 5 Rs to Homeostasis</h2>
      <p>Our proprietary framework guides every member's journey:</p>
      <ol>
        <li><strong>Reduce</strong> - Detoxification and parasite elimination</li>
        <li><strong>Rebalance</strong> - Gut biome restoration</li>
        <li><strong>Reactivate</strong> - ECS optimization</li>
        <li><strong>Restore</strong> - Mitochondrial regeneration with 90 essential nutrients</li>
        <li><strong>Revitalize</strong> - Mind-body-spirit integration</li>
      </ol>

      <p style="text-align: center;">
        <a href="${FFPMA_BRAND.siteUrl}" class="cta-button">Explore ALLIO</a>
      </p>

      <hr class="divider">
      <p style="font-style: italic; color: #94a3b8;">"Merging humans with AI by healing." - The ALLIO Mission</p>
      `,
      'ALLIO v1 launches April 1, 2026 - AI-powered healing for our PMA members'
    );
    return { subject, html };
  },

  appointmentReminder(memberName: string, doctorName: string, dateStr: string, timeStr: string): { subject: string; html: string } {
    const subject = `Appointment Reminder - ${doctorName} on ${dateStr}`;
    const html = wrapInBrandedTemplate(
      'Appointment Reminder',
      `
      <p>Dear ${memberName},</p>
      <p>This is a reminder that you have an upcoming appointment:</p>

      <div class="highlight">
        <strong>Doctor:</strong> ${doctorName}<br>
        <strong>Date:</strong> ${dateStr}<br>
        <strong>Time:</strong> ${timeStr}
      </div>

      <h3>Please prepare:</h3>
      <ul>
        <li>Any recent lab results or test results</li>
        <li>Current supplement list</li>
        <li>Questions about your protocol</li>
        <li>Updates on symptoms or progress</li>
      </ul>

      <p>If you need to reschedule, please contact us at least 24 hours in advance.</p>

      <p style="text-align: center;">
        <a href="${FFPMA_BRAND.siteUrl}/member" class="cta-button">View Appointment Details</a>
      </p>
      `,
      `Reminder: Your appointment with ${doctorName} is on ${dateStr}`
    );
    return { subject, html };
  },
};

export async function sendCampaignEmail(
  to: string,
  template: { subject: string; html: string }
): Promise<{ success: boolean; messageId?: string; error?: string }> {
  return sendEmail(to, template.subject, template.html);
}

export async function sendBulkCampaign(
  recipients: string[],
  template: { subject: string; html: string },
  delayMs: number = 1000
): Promise<{ sent: number; failed: number; errors: string[] }> {
  let sent = 0;
  let failed = 0;
  const errors: string[] = [];

  for (const email of recipients) {
    try {
      const result = await sendEmail(email, template.subject, template.html);
      if (result.success) {
        sent++;
      } else {
        failed++;
        errors.push(`${email}: ${result.error}`);
      }
      if (delayMs > 0) {
        await new Promise(resolve => setTimeout(resolve, delayMs));
      }
    } catch (err: any) {
      failed++;
      errors.push(`${email}: ${err.message}`);
    }
  }

  return { sent, failed, errors };
}
