export interface LegalDocumentContent {
  title: string;
  slug: string;
  lastUpdated: string;
  content: string;
}

const EFFECTIVE_DATE = 'April 1, 2026';
const LAST_UPDATED = 'March 13, 2026';

export function getPMAMemberAgreement(): LegalDocumentContent {
  return {
    title: 'PMA Member Agreement',
    slug: 'pma-agreement',
    lastUpdated: LAST_UPDATED,
    content: `
# PRIVATE MEMBER ASSOCIATION AGREEMENT
## Forgotten Formula PMA

**Effective Date:** ${EFFECTIVE_DATE}
**Last Updated:** ${LAST_UPDATED}

---

## PREAMBLE

This Private Member Association Agreement ("Agreement") is entered into between Forgotten Formula PMA ("the Association") and the undersigned individual ("Member"). This Agreement establishes the rights, responsibilities, and protections of membership in a Private Member Association operating under the protections of the First and Fourteenth Amendments to the United States Constitution.

## ARTICLE I: PURPOSE AND MISSION

The Association exists to provide its Members with access to holistic health information, natural healing modalities, nutritional products, and practitioner networks. The Association operates on the principle of **healing over profits** and **nature over synthetic solutions**.

## ARTICLE II: MEMBERSHIP

### 2.1 Eligibility
Membership is open to any natural person who:
- Is at least 18 years of age
- Agrees to the terms of this Agreement
- Shares the Association's commitment to natural health and healing

### 2.2 Membership Rights
Members have the right to:
- Access the Association's product catalog and services
- Receive personalized health protocols generated by the ALLIO AI system
- Consult with network practitioners and physicians
- Participate in training programs and educational content
- Access AI-powered support agents for health guidance

### 2.3 Membership Responsibilities
Members agree to:
- Use products and services for personal health purposes only
- Not redistribute or resell Association products commercially
- Maintain the confidentiality of proprietary protocols and information
- Report any adverse reactions to products or protocols promptly

## ARTICLE III: PRIVACY AND CONFIDENTIALITY

### 3.1 Health Information
The Association collects health information through intake forms, consultations, and AI interactions solely for the purpose of providing personalized healing protocols. This information is protected under PMA privacy principles and is not shared with government agencies, insurance companies, or third parties without Member consent.

### 3.2 Data Security
Member data is stored using encrypted databases with access controls. AI agents process health data in accordance with the Association's data governance policies.

## ARTICLE IV: PRODUCTS AND SERVICES

### 4.1 Product Quality
All products offered through the Association are CGMP-manufactured and include Certificates of Analysis (COA) where applicable.

### 4.2 AI Services Disclaimer
The ALLIO AI system and its specialized agents provide informational guidance only. AI-generated protocols are reviewed by qualified practitioners and do not constitute medical advice from a licensed physician unless explicitly provided by a network doctor.

### 4.3 Practitioner Network
Network practitioners are independent professionals who have agreed to the Association's standards of care. The Association facilitates connections but does not employ practitioners directly.

## ARTICLE V: LIMITATION OF LIABILITY

The Association, its officers, agents (including AI agents), and practitioners shall not be liable for any indirect, incidental, or consequential damages arising from membership or use of products and services. Members acknowledge that natural health approaches involve individual variability in outcomes.

## ARTICLE VI: DISPUTE RESOLUTION

Any disputes between Members and the Association shall be resolved through binding arbitration in accordance with the rules of the American Arbitration Association, conducted in Denton County, Texas.

## ARTICLE VII: TERMINATION

Either party may terminate this Agreement with 30 days written notice. Upon termination, the Member's access to products and services will cease, but previously generated protocols and educational materials may be retained for personal use.

---

**By signing this Agreement, the Member acknowledges that they have read, understood, and agree to be bound by its terms.**

_Forgotten Formula PMA_
_Justin, TX 76247_
    `.trim(),
  };
}

export function getPrivacyPolicy(): LegalDocumentContent {
  return {
    title: 'Privacy Policy',
    slug: 'privacy-policy',
    lastUpdated: LAST_UPDATED,
    content: `
# PRIVACY POLICY
## Forgotten Formula PMA

**Effective Date:** ${EFFECTIVE_DATE}
**Last Updated:** ${LAST_UPDATED}

---

## 1. INTRODUCTION

Forgotten Formula PMA ("we," "us," "the Association") is committed to protecting the privacy of our Members. This Privacy Policy describes how we collect, use, store, and protect your personal and health information within our Private Member Association.

## 2. INFORMATION WE COLLECT

### 2.1 Personal Information
- Full name, email address, phone number, and mailing address
- Date of birth and age
- Account credentials

### 2.2 Health Information
- Patient intake form data including health history, current conditions, and medications
- Blood analysis results and images
- AI-generated health protocols and recommendations
- Consultation notes from network practitioners
- Supplement and product purchase history

### 2.3 Technical Information
- Browser type and device information
- IP address and session data
- Usage patterns within the member portal

## 3. HOW WE USE YOUR INFORMATION

We use collected information to:
- Generate personalized healing protocols through our ALLIO AI system
- Facilitate consultations with network practitioners
- Process product orders and membership management
- Send relevant health communications and appointment reminders
- Improve our AI agents' ability to serve Members
- Maintain Association records and compliance

## 4. INFORMATION SHARING

We do NOT share your information with:
- Government agencies (unless required by valid legal process)
- Insurance companies
- Pharmaceutical companies
- Data brokers or advertisers

We may share information with:
- Network practitioners you choose to consult with
- Payment processors (Stripe) for transaction processing only
- Contract management services (SignNow) for document signing

## 5. DATA SECURITY

We implement industry-standard security measures including:
- Encrypted database storage (PostgreSQL with SSL)
- Session-based authentication with secure cookies
- API key authentication for internal agent communications
- Regular security audits by our SENTINEL orchestration system
- Access controls limiting data visibility by role

## 6. AI DATA PROCESSING

Our ALLIO AI system processes health data to:
- Analyze intake form responses for protocol generation
- Provide personalized product recommendations
- Support blood microscopy analysis
- Deliver nutritional and supplement guidance

AI-generated outputs are informational and supplementary to practitioner guidance. AI agents do not make autonomous medical decisions.

## 7. DATA RETENTION

- Active member data is retained for the duration of membership plus 3 years
- Health protocols are retained indefinitely for member reference
- Transaction records are retained for 7 years per tax requirements
- AI interaction logs are retained for 90 days for quality improvement

## 8. YOUR RIGHTS

As a Member, you have the right to:
- Access your personal and health information
- Request correction of inaccurate data
- Request deletion of your data (subject to retention requirements)
- Export your health protocols and records
- Opt out of non-essential communications

## 9. CONTACT

For privacy-related inquiries:
- Email: blake@forgottenformula.com
- Mail: Forgotten Formula PMA, Justin, TX 76247

## 10. CHANGES TO THIS POLICY

We may update this Privacy Policy periodically. Members will be notified of material changes via email and dashboard notification.

---

_Forgotten Formula PMA_
_Justin, TX 76247_
    `.trim(),
  };
}

export function getTermsOfService(): LegalDocumentContent {
  return {
    title: 'Terms of Service',
    slug: 'terms',
    lastUpdated: LAST_UPDATED,
    content: `
# TERMS OF SERVICE
## Forgotten Formula PMA

**Effective Date:** ${EFFECTIVE_DATE}
**Last Updated:** ${LAST_UPDATED}

---

## 1. ACCEPTANCE OF TERMS

By accessing or using the Forgotten Formula PMA platform ("Platform"), including the ALLIO AI system, member portal, product catalog, and related services, you agree to be bound by these Terms of Service ("Terms"). If you do not agree, do not use the Platform.

## 2. DESCRIPTION OF SERVICES

The Platform provides:
- AI-powered health protocol generation via the ALLIO system
- Access to 320+ CGMP-manufactured health products
- 58+ educational training modules with certifications
- Blood microscopy analysis with AI assistance
- Network practitioner consultations
- Personalized supplement and nutrition guidance
- Research database access (ECS pathways, peptide protocols, etc.)

## 3. MEMBER ACCOUNTS

### 3.1 Registration
You must provide accurate information during registration. You are responsible for maintaining the confidentiality of your account credentials.

### 3.2 Account Security
Notify us immediately of any unauthorized access. We employ session-based authentication, rate limiting, and encrypted storage to protect your account.

## 4. AI SERVICES DISCLAIMER

### 4.1 Informational Purpose
All AI-generated content, including health protocols, product recommendations, and nutritional guidance, is provided for informational purposes within the PMA context. It does not constitute licensed medical advice unless explicitly provided by a licensed network practitioner.

### 4.2 No Guarantee of Outcomes
Health outcomes vary by individual. The Association makes no guarantees regarding the effectiveness of protocols, products, or treatments.

### 4.3 AI Limitations
AI agents operate within their defined specialties and may occasionally provide incomplete or imprecise information. Critical health decisions should be made in consultation with a qualified practitioner.

## 5. PRODUCTS AND ORDERS

### 5.1 Product Information
Product descriptions, ingredients, and pricing are provided as accurately as possible. Prices are subject to change.

### 5.2 Payment
Payments are processed through Stripe. By making a purchase, you agree to Stripe's terms of service.

### 5.3 Shipping
Products are shipped to the address provided. Shipping times vary by location and product availability.

### 5.4 Returns
Products may be returned within 30 days of receipt if unopened and in original condition. Perishable and opened products are not eligible for return.

## 6. INTELLECTUAL PROPERTY

All content on the Platform, including training modules, protocols, AI agent outputs, brand assets, and the ALLIO system, is the intellectual property of Forgotten Formula PMA. Members may use content for personal health purposes only.

## 7. PROHIBITED CONDUCT

Members shall not:
- Use the Platform for commercial redistribution of products or content
- Attempt to reverse-engineer or exploit AI systems
- Misrepresent AI-generated content as licensed medical advice
- Share account credentials with non-members
- Upload malicious content or attempt to compromise Platform security

## 8. LIMITATION OF LIABILITY

TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE ASSOCIATION SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES ARISING FROM USE OF THE PLATFORM OR ITS SERVICES.

## 9. GOVERNING LAW

These Terms are governed by the laws of the State of Texas. Any disputes shall be resolved through binding arbitration in Denton County, Texas.

## 10. MODIFICATIONS

We reserve the right to modify these Terms at any time. Continued use of the Platform after modifications constitutes acceptance.

---

_Forgotten Formula PMA_
_Justin, TX 76247_
    `.trim(),
  };
}

export function getDoctorOnboardingContract(): LegalDocumentContent {
  return {
    title: 'Doctor Onboarding Agreement',
    slug: 'doctor-agreement',
    lastUpdated: LAST_UPDATED,
    content: `
# PRACTITIONER ONBOARDING AGREEMENT
## Forgotten Formula PMA - Doctor Network

**Effective Date:** ${EFFECTIVE_DATE}
**Last Updated:** ${LAST_UPDATED}

---

## 1. PURPOSE

This Agreement establishes the terms under which a licensed healthcare practitioner ("Practitioner") joins the Forgotten Formula PMA practitioner network to provide consultative services to Association Members.

## 2. PRACTITIONER QUALIFICATIONS

The Practitioner represents that they:
- Hold a valid, unrestricted license to practice in their jurisdiction
- Have experience in functional, integrative, or naturopathic medicine
- Are committed to root cause medicine and holistic healing approaches
- Will maintain appropriate malpractice insurance coverage

## 3. SCOPE OF SERVICES

### 3.1 Consultations
The Practitioner may provide health consultations to Members, including:
- Review of AI-generated health protocols
- Blood analysis interpretation
- Supplement and treatment recommendations
- Follow-up care and protocol adjustments

### 3.2 AI Collaboration
The Practitioner will work alongside the ALLIO AI system, which provides:
- Patient intake analysis and protocol drafts
- Research database access
- Product catalog integration
- Appointment scheduling and reminders

### 3.3 Independence
The Practitioner operates as an independent contractor, not an employee of the Association. The Practitioner maintains full clinical autonomy in all patient care decisions.

## 4. COMPENSATION

Compensation terms are established separately based on the Practitioner's engagement model (per-consultation, retainer, or revenue-sharing). All compensation arrangements are documented in a supplementary schedule.

## 5. COMPLIANCE

### 5.1 PMA Framework
The Practitioner agrees to operate within the PMA framework, understanding that services are provided to private association members, not the general public.

### 5.2 Record Keeping
The Practitioner agrees to maintain appropriate clinical records and contribute relevant findings to the member's health profile within the Platform.

### 5.3 Confidentiality
All member health information accessed through the Platform is confidential and subject to the Association's Privacy Policy.

## 6. TRAINING AND CERTIFICATION

The Practitioner has access to 58+ training modules covering:
- Live blood analysis techniques
- Peptide protocols and administration
- ECS (Endocannabinoid System) pathway optimization
- Frequency medicine and PEMF therapy
- The 5 Rs to Homeostasis framework

Completion of designated modules is recommended for optimal use of the ALLIO platform.

## 7. TERMINATION

Either party may terminate this Agreement with 60 days written notice. The Practitioner shall complete any active patient engagements or arrange appropriate referrals before departure.

## 8. DISPUTE RESOLUTION

Disputes shall be resolved through mediation, followed by binding arbitration if necessary, in Denton County, Texas.

---

_Forgotten Formula PMA_
_Justin, TX 76247_
    `.trim(),
  };
}

export function getAllLegalDocuments(): LegalDocumentContent[] {
  return [
    getPMAMemberAgreement(),
    getPrivacyPolicy(),
    getTermsOfService(),
    getDoctorOnboardingContract(),
  ];
}

export function getLegalDocumentBySlug(slug: string): LegalDocumentContent | null {
  const docs = getAllLegalDocuments();
  return docs.find(d => d.slug === slug) || null;
}
