import PDFDocument from "pdfkit";
import type {
  HealingProtocol,
  PatientProfile,
} from "@shared/types/protocol-assembly";

const COLORS = {
  primary: "#331A80",
  secondary: "#6644BB",
  accent: "#8B6FCC",
  text: "#222222",
  lightText: "#666666",
  headerBg: "#F0EBF8",
  white: "#FFFFFF",
  border: "#CCCCCC",
};

function addHeader(doc: PDFKit.PDFDocument, text: string) {
  doc.moveDown(0.5);
  doc
    .fontSize(18)
    .fillColor(COLORS.primary)
    .text(text, { underline: true });
  doc.moveDown(0.3);
}

function addSubheader(doc: PDFKit.PDFDocument, text: string) {
  doc.moveDown(0.3);
  doc.fontSize(14).fillColor(COLORS.secondary).text(text);
  doc.moveDown(0.2);
}

function addBody(doc: PDFKit.PDFDocument, text: string) {
  doc.fontSize(10).fillColor(COLORS.text).text(text);
}

function addBullet(doc: PDFKit.PDFDocument, text: string) {
  doc.fontSize(10).fillColor(COLORS.text).text(`  \u2022 ${text}`, { indent: 10 });
}

function checkPage(doc: PDFKit.PDFDocument, needed: number = 80) {
  if (doc.y > doc.page.height - doc.page.margins.bottom - needed) {
    doc.addPage();
  }
}

export function generateProtocolPDF(
  protocol: HealingProtocol,
  profile: PatientProfile,
  citations?: Array<{ title: string; authors: string[]; journal?: string; year?: string; url?: string }>
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: "LETTER",
        margins: { top: 60, bottom: 60, left: 55, right: 55 },
        info: {
          Title: `${protocol.patientName} - Healing Protocol`,
          Author: "Forgotten Formula PMA - DR. FORMULA",
          Subject: "Personalized Healing Protocol",
        },
      });

      const chunks: Buffer[] = [];
      doc.on("data", (chunk: Buffer) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);

      doc
        .fontSize(28)
        .fillColor(COLORS.primary)
        .text("FORGOTTEN FORMULA PMA", { align: "center" });
      doc.moveDown(0.3);
      doc
        .fontSize(20)
        .fillColor(COLORS.secondary)
        .text("Personalized Healing Protocol", { align: "center" });
      doc.moveDown(0.5);
      doc
        .fontSize(14)
        .fillColor(COLORS.text)
        .text(protocol.patientName, { align: "center" });
      doc
        .fontSize(11)
        .fillColor(COLORS.lightText)
        .text(`Generated: ${protocol.generatedDate} | Duration: ${protocol.protocolDurationDays} days`, {
          align: "center",
        });
      doc.moveDown(0.5);
      doc
        .moveTo(55, doc.y)
        .lineTo(doc.page.width - 55, doc.y)
        .strokeColor(COLORS.secondary)
        .lineWidth(2)
        .stroke();
      doc.moveDown(0.5);
      doc
        .fontSize(9)
        .fillColor(COLORS.lightText)
        .text(
          "This protocol is for private membership association use only. Generated by DR. FORMULA, Chief Medical Protocol Agent.",
          { align: "center" }
        );

      doc.addPage();
      addHeader(doc, "EXECUTIVE SUMMARY");
      addBody(doc, protocol.summary || "");
      doc.moveDown(0.5);

      addSubheader(doc, "Patient Overview");
      addBody(doc, `Name: ${protocol.patientName}`);
      addBody(doc, `Age: ${protocol.patientAge}`);
      addBody(doc, `Gender: ${profile.gender || "N/A"}`);
      if (profile.location) addBody(doc, `Location: ${profile.location}`);
      doc.moveDown(0.3);

      if (profile.chiefComplaints?.length > 0) {
        addSubheader(doc, "Chief Complaints");
        profile.chiefComplaints.forEach((c) => addBullet(doc, c));
      }

      if (profile.currentDiagnoses?.length > 0) {
        addSubheader(doc, "Current Diagnoses");
        profile.currentDiagnoses.forEach((d) => addBullet(doc, d));
      }

      if (profile.goals?.length > 0) {
        addSubheader(doc, "Patient Goals");
        profile.goals.forEach((g) => addBullet(doc, g));
      }

      doc.addPage();
      addHeader(doc, "ROOT CAUSE ANALYSIS");
      if (protocol.rootCauseAnalysis?.length > 0) {
        protocol.rootCauseAnalysis.forEach((rc) => {
          checkPage(doc, 60);
          doc
            .fontSize(12)
            .fillColor(COLORS.secondary)
            .text(`${rc.rank}. ${rc.cause} (${rc.category.toUpperCase()})`);
          doc.fontSize(10).fillColor(COLORS.text).text(`   ${rc.details}`);
          if (rc.relatedSymptoms?.length > 0) {
            doc
              .fontSize(9)
              .fillColor(COLORS.lightText)
              .text(`   Related: ${rc.relatedSymptoms.join(", ")}`);
          }
          doc.moveDown(0.3);
        });
      }

      if (protocol.phases?.length > 0) {
        doc.addPage();
        addHeader(doc, "THE 5 Rs — TREATMENT PHASES");
        protocol.phases.forEach((phase) => {
          checkPage(doc, 80);
          doc
            .fontSize(13)
            .fillColor(COLORS.primary)
            .text(`Phase ${phase.phaseNumber}: ${phase.name} (${phase.weekRange})`);
          doc.fontSize(10).fillColor(COLORS.text).text(`Focus: ${phase.focus}`);
          phase.keyActions?.forEach((action) => addBullet(doc, action));
          doc.moveDown(0.4);
        });
      }

      if (protocol.injectablePeptides?.length > 0) {
        doc.addPage();
        addHeader(doc, "INJECTABLE PEPTIDE PROTOCOL");
        protocol.injectablePeptides.forEach((p) => {
          checkPage(doc, 90);
          doc.fontSize(12).fillColor(COLORS.secondary).text(p.name);
          addBody(doc, `Vial: ${p.vialSize} | Reconstitution: ${p.reconstitution}`);
          addBody(doc, `Dose: ${p.dose} | Route: ${p.route} | Frequency: ${p.frequency}`);
          addBody(doc, `Duration: ${p.duration} | Purpose: ${p.purpose}`);
          if (p.notes) {
            doc.fontSize(9).fillColor(COLORS.lightText).text(`Note: ${p.notes}`);
          }
          doc.moveDown(0.3);
        });
      }

      if (protocol.oralPeptides?.length > 0) {
        checkPage(doc, 100);
        addHeader(doc, "ORAL PEPTIDES");
        protocol.oralPeptides.forEach((p) => {
          checkPage(doc, 50);
          addBody(doc, `${p.name}: ${p.dose}, ${p.frequency} for ${p.duration} — ${p.purpose}`);
        });
      }

      if (protocol.bioregulators?.length > 0) {
        checkPage(doc, 100);
        addHeader(doc, "BIOREGULATORS");
        protocol.bioregulators.forEach((b) => {
          checkPage(doc, 50);
          addBody(doc, `${b.name} → ${b.targetOrgan}: ${b.dose}, ${b.frequency} for ${b.duration}`);
        });
      }

      if (protocol.ivTherapies?.length > 0) {
        checkPage(doc, 100);
        addHeader(doc, "IV THERAPY SCHEDULE");
        protocol.ivTherapies.forEach((iv) => {
          checkPage(doc, 50);
          addBody(doc, `${iv.name}: ${iv.frequency} for ${iv.duration} — ${iv.purpose}`);
          if (iv.notes) {
            doc.fontSize(9).fillColor(COLORS.lightText).text(`   ${iv.notes}`);
          }
        });
      }

      if (protocol.imTherapies?.length > 0) {
        checkPage(doc, 100);
        addHeader(doc, "IM THERAPY SCHEDULE");
        protocol.imTherapies.forEach((im) => {
          checkPage(doc, 50);
          addBody(doc, `${im.name}: ${im.dose}, ${im.frequency} — ${im.purpose}`);
        });
      }

      if (protocol.supplements?.length > 0) {
        doc.addPage();
        addHeader(doc, "SUPPLEMENT STACK");
        protocol.supplements.forEach((s) => {
          checkPage(doc, 40);
          addBullet(doc, `${s.name} — ${s.dose} (${s.timing}) → ${s.purpose}`);
        });
      }

      if (protocol.detoxProtocols?.length > 0) {
        doc.addPage();
        addHeader(doc, "DETOX PROTOCOLS");
        protocol.detoxProtocols.forEach((d) => {
          checkPage(doc, 70);
          doc.fontSize(12).fillColor(COLORS.secondary).text(d.name);
          addBody(doc, `Method: ${d.method}`);
          addBody(doc, `Frequency: ${d.frequency} | Duration: ${d.duration}`);
          addBody(doc, `Instructions: ${d.instructions}`);
          doc.moveDown(0.3);
        });
      }

      if (protocol.parasiteAntiviralProtocols?.length > 0) {
        checkPage(doc, 100);
        addHeader(doc, "PARASITE & ANTIVIRAL PROTOCOLS");
        protocol.parasiteAntiviralProtocols.forEach((p) => {
          checkPage(doc, 50);
          addBody(doc, `${p.name}: ${p.dose} — ${p.schedule} for ${p.duration}`);
          addBody(doc, `Purpose: ${p.purpose}`);
          doc.moveDown(0.2);
        });
      }

      if (protocol.dailySchedule) {
        doc.addPage();
        addHeader(doc, "DAILY SCHEDULE");
        const periods = ["morning", "midday", "evening", "bedtime"] as const;
        periods.forEach((period) => {
          const items = protocol.dailySchedule[period];
          if (items?.length > 0) {
            checkPage(doc, 60);
            addSubheader(doc, period.charAt(0).toUpperCase() + period.slice(1));
            items.forEach((item) => {
              addBullet(
                doc,
                `${item.time ? `[${item.time}] ` : ""}${item.item}${item.details ? ` — ${item.details}` : ""}${item.frequency ? ` (${item.frequency})` : ""}`
              );
            });
          }
        });
      }

      if (protocol.lifestyleRecommendations?.length > 0 || protocol.dietaryGuidelines?.length > 0) {
        doc.addPage();
        addHeader(doc, "LIFESTYLE & DIETARY GUIDELINES");

        if (protocol.lifestyleRecommendations?.length > 0) {
          addSubheader(doc, "Lifestyle Recommendations");
          protocol.lifestyleRecommendations.forEach((l) => {
            checkPage(doc, 40);
            addBullet(doc, `${l.category}: ${l.recommendation}${l.details ? ` — ${l.details}` : ""}`);
          });
        }

        if (protocol.dietaryGuidelines?.length > 0) {
          addSubheader(doc, "Dietary Guidelines");
          protocol.dietaryGuidelines.forEach((d) => addBullet(doc, d));
        }
      }

      if (protocol.followUpPlan?.length > 0 || protocol.labsRequired?.length > 0) {
        doc.addPage();
        addHeader(doc, "FOLLOW-UP PLAN & LAB ORDERS");

        if (protocol.followUpPlan?.length > 0) {
          addSubheader(doc, "Follow-Up Schedule");
          protocol.followUpPlan.forEach((f) => {
            checkPage(doc, 40);
            addBullet(doc, `Week ${f.weekNumber}: ${f.action}${f.details ? ` — ${f.details}` : ""}`);
          });
        }

        if (protocol.labsRequired?.length > 0) {
          addSubheader(doc, "Required Labs");
          protocol.labsRequired.forEach((l) => addBullet(doc, l));
        }
      }

      if (protocol.contraindications?.length > 0) {
        checkPage(doc, 80);
        addHeader(doc, "CONTRAINDICATIONS & WARNINGS");
        protocol.contraindications.forEach((c) => addBullet(doc, c));
      }

      const allProducts: Array<{ name: string; category: string; dose?: string }> = [];
      protocol.injectablePeptides?.forEach((p) =>
        allProducts.push({ name: p.name, category: "Injectable Peptide", dose: p.dose })
      );
      protocol.oralPeptides?.forEach((p) =>
        allProducts.push({ name: p.name, category: "Oral Peptide", dose: p.dose })
      );
      protocol.bioregulators?.forEach((b) =>
        allProducts.push({ name: b.name, category: "Bioregulator", dose: b.dose })
      );
      protocol.supplements?.forEach((s) =>
        allProducts.push({ name: s.name, category: "Supplement", dose: s.dose })
      );
      protocol.ivTherapies?.forEach((iv) =>
        allProducts.push({ name: iv.name, category: "IV Therapy" })
      );
      protocol.imTherapies?.forEach((im) =>
        allProducts.push({ name: im.name, category: "IM Therapy", dose: im.dose })
      );
      protocol.detoxProtocols?.forEach((d) =>
        allProducts.push({ name: d.name, category: "Detox" })
      );
      protocol.parasiteAntiviralProtocols?.forEach((p) =>
        allProducts.push({ name: p.name, category: "Antiparasitic/Antiviral", dose: p.dose })
      );

      if (allProducts.length > 0) {
        doc.addPage();
        addHeader(doc, "SHOPPING LIST — FFPMA CATALOG");
        addBody(doc, `Total items: ${allProducts.length}`);
        doc.moveDown(0.3);

        const grouped = new Map<string, typeof allProducts>();
        allProducts.forEach((p) => {
          const list = grouped.get(p.category) || [];
          list.push(p);
          grouped.set(p.category, list);
        });

        grouped.forEach((items, category) => {
          checkPage(doc, 50);
          addSubheader(doc, category);
          items.forEach((item) => {
            addBullet(doc, `${item.name}${item.dose ? ` — ${item.dose}` : ""}`);
          });
        });
      }

      if (citations && citations.length > 0) {
        doc.addPage();
        addHeader(doc, "RESEARCH CITATIONS");
        addBody(doc, "Peer-reviewed evidence supporting major interventions:");
        doc.moveDown(0.3);

        citations.forEach((cite, idx) => {
          checkPage(doc, 60);
          const authorStr = cite.authors?.slice(0, 3).join(", ") || "Unknown authors";
          const yearStr = cite.year || "n.d.";
          const journalStr = cite.journal ? ` ${cite.journal}.` : "";
          doc
            .fontSize(9)
            .fillColor(COLORS.text)
            .text(`[${idx + 1}] ${authorStr} (${yearStr}). "${cite.title}."${journalStr}`, {
              link: cite.url || undefined,
            });
          doc.moveDown(0.2);
        });
      }

      doc.addPage();
      doc.moveDown(2);
      doc
        .fontSize(11)
        .fillColor(COLORS.lightText)
        .text("DISCLAIMER", { align: "center", underline: true });
      doc.moveDown(0.5);
      doc
        .fontSize(9)
        .fillColor(COLORS.lightText)
        .text(
          "This protocol has been generated by DR. FORMULA, Chief Medical Protocol Agent of Forgotten Formula PMA. " +
            "This document is intended solely for private membership association (PMA) use and does not constitute medical advice, " +
            "diagnosis, or treatment in the public domain. All protocols are recommendations subject to Trustee review and refinement. " +
            "Member sovereignty and informed consent are foundational principles of this association.",
          { align: "center" }
        );
      doc.moveDown(1);
      doc
        .fontSize(10)
        .fillColor(COLORS.secondary)
        .text(
          '"Your body is a self-healing organism. My job is to identify what\'s blocking that healing and give you the tools to remove those blocks."',
          { align: "center", oblique: true }
        );
      doc.moveDown(0.3);
      doc.fontSize(10).fillColor(COLORS.primary).text("— DR. FORMULA", { align: "center" });

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}
