// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/landing-layouts/BentoGrid.tsx": () => import("../components/mockups/landing-layouts/BentoGrid.tsx"),
  "./components/mockups/landing-layouts/HorizontalFlow.tsx": () => import("../components/mockups/landing-layouts/HorizontalFlow.tsx"),
  "./components/mockups/landing-layouts/SplitPanel.tsx": () => import("../components/mockups/landing-layouts/SplitPanel.tsx")
};
