import { db } from "../db";
import { eq, inArray } from "drizzle-orm";
import { quizzes, quizQuestions, quizAnswers } from "@shared/schema";

const CERT_EXAM_ID = "quiz-lba-certification";

const CERT_EXAM_QUESTIONS: Array<{
  id: string;
  text: string;
  explanation: string;
  answers: Array<{ text: string; isCorrect: boolean }>;
}> = [
  { id: "ce-01", text: "Who is credited with originating the theory of pleomorphism?", explanation: "Antoine Bechamp proposed pleomorphism — the theory that microorganisms can change form based on the host's internal environment.", answers: [{ text: "Antoine Bechamp", isCorrect: true }, { text: "Louis Pasteur", isCorrect: false }, { text: "Robert Koch", isCorrect: false }, { text: "Rudolf Virchow", isCorrect: false }] },
  { id: "ce-02", text: "What is the smallest living unit in Enderlein's cyclogeny?", explanation: "The protit is the smallest living protein colloidal particle, the base of all microbial development in Enderlein's system.", answers: [{ text: "Protit", isCorrect: true }, { text: "Bacterium", isCorrect: false }, { text: "Virus", isCorrect: false }, { text: "Spore", isCorrect: false }] },
  { id: "ce-03", text: "What does cyclogeny describe?", explanation: "Cyclogeny is Enderlein's theory of the developmental cycle of microorganisms from colloidal protits through bacterial stages to fungal culmination.", answers: [{ text: "Developmental cycle of microorganisms from protits to fungi", isCorrect: true }, { text: "The cell division cycle", isCorrect: false }, { text: "Human aging process", isCorrect: false }, { text: "Seasonal disease patterns", isCorrect: false }] },
  { id: "ce-04", text: "What type of microscopy is primarily used for LBA?", explanation: "Dark field microscopy reveals structures by blocking direct light, allowing only scattered light from the specimen to enter the objective.", answers: [{ text: "Dark field microscopy", isCorrect: true }, { text: "Electron microscopy", isCorrect: false }, { text: "Fluorescence microscopy", isCorrect: false }, { text: "Confocal microscopy", isCorrect: false }] },
  { id: "ce-05", text: "What minimum magnification is required for LBA practice?", explanation: "1000x magnification with oil immersion is required for detailed morphological and pleomorphic form identification.", answers: [{ text: "1000x with oil immersion", isCorrect: true }, { text: "100x dry", isCorrect: false }, { text: "400x", isCorrect: false }, { text: "40x", isCorrect: false }] },
  { id: "ce-06", text: "What does Kohler illumination achieve?", explanation: "Kohler illumination provides even, consistent illumination by properly aligning the field diaphragm, condenser, and light path.", answers: [{ text: "Even, consistent illumination for optimal imaging", isCorrect: true }, { text: "Increased magnification", isCorrect: false }, { text: "Specimen staining", isCorrect: false }, { text: "Phase contrast", isCorrect: false }] },
  { id: "ce-07", text: "Why is the first blood drop discarded during LBA collection?", explanation: "The first drop contains tissue fluid that dilutes the sample and creates artifacts.", answers: [{ text: "It contains tissue fluid that creates artifacts", isCorrect: true }, { text: "It is contaminated by alcohol", isCorrect: false }, { text: "It has too many platelets", isCorrect: false }, { text: "It is too cold", isCorrect: false }] },
  { id: "ce-08", text: "What is the optimal observation window for a live blood sample?", explanation: "Blood changes immediately upon leaving the body; the optimal window is 15-20 minutes before artifacts dominate.", answers: [{ text: "15-20 minutes", isCorrect: true }, { text: "1 hour", isCorrect: false }, { text: "5 minutes", isCorrect: false }, { text: "3 hours", isCorrect: false }] },
  { id: "ce-09", text: "How many zones does the FFPMA systematic observation protocol include?", explanation: "The FFPMA 5-Zone Protocol covers: Center Field, Peripheral Scan, Plasma Quality, Cell Interaction, Dynamic Assessment.", answers: [{ text: "5", isCorrect: true }, { text: "3", isCorrect: false }, { text: "8", isCorrect: false }, { text: "10", isCorrect: false }] },
  { id: "ce-10", text: "What is the normal diameter of a red blood cell?", explanation: "Normal RBCs are 7-8 micrometers, serving as an internal size reference.", answers: [{ text: "7-8 micrometers", isCorrect: true }, { text: "2-4 micrometers", isCorrect: false }, { text: "15-20 micrometers", isCorrect: false }, { text: "50 micrometers", isCorrect: false }] },
  { id: "ce-11", text: "What causes rouleaux formation in LBA?", explanation: "Elevated fibrinogen, immunoglobulins, and inflammatory proteins reduce zeta potential, causing RBCs to stack.", answers: [{ text: "Elevated plasma proteins reducing zeta potential", isCorrect: true }, { text: "Cold temperature only", isCorrect: false }, { text: "Genetic mutation", isCorrect: false }, { text: "Equipment malfunction", isCorrect: false }] },
  { id: "ce-12", text: "How do echinocytes differ from acanthocytes?", explanation: "Echinocytes have regular, evenly spaced spicules (10-30); acanthocytes have irregular, variable-length spicules (3-12).", answers: [{ text: "Echinocytes: regular even spicules; Acanthocytes: irregular uneven spicules", isCorrect: true }, { text: "They are identical", isCorrect: false }, { text: "Size difference only", isCorrect: false }, { text: "Color difference only", isCorrect: false }] },
  { id: "ce-13", text: "What does echinocyte formation primarily indicate?", explanation: "Echinocytes indicate oxidative stress, EFA imbalance, and membrane lipid peroxidation.", answers: [{ text: "Oxidative stress and fatty acid imbalance", isCorrect: true }, { text: "Iron deficiency", isCorrect: false }, { text: "Bacterial infection", isCorrect: false }, { text: "B12 deficiency", isCorrect: false }] },
  { id: "ce-14", text: "What condition is associated with target cells (codocytes)?", explanation: "Target cells with their characteristic bulls-eye pattern are seen in liver disease, hemoglobinopathies, and iron deficiency.", answers: [{ text: "Liver disease, hemoglobinopathies, iron deficiency", isCorrect: true }, { text: "Oxidative stress only", isCorrect: false }, { text: "Dehydration", isCorrect: false }, { text: "Viral infection", isCorrect: false }] },
  { id: "ce-15", text: "What vitality score range indicates excellent RBC health?", explanation: "9-10 indicates excellent: round uniform discs, free-flowing, smooth membranes, good flexibility, consistent size.", answers: [{ text: "9-10", isCorrect: true }, { text: "5-6", isCorrect: false }, { text: "3-4", isCorrect: false }, { text: "1-2", isCorrect: false }] },
  { id: "ce-16", text: "What does microcytosis (small RBCs) most commonly indicate?", explanation: "Microcytic RBCs (<7 micrometers) most commonly indicate iron deficiency anemia or thalassemia.", answers: [{ text: "Iron deficiency or thalassemia", isCorrect: true }, { text: "B12 deficiency", isCorrect: false }, { text: "Oxidative stress", isCorrect: false }, { text: "Dehydration", isCorrect: false }] },
  { id: "ce-17", text: "Which is the most abundant white blood cell type?", explanation: "Neutrophils comprise 50-70% of all WBCs and are the primary bacterial defense cells.", answers: [{ text: "Neutrophils (50-70%)", isCorrect: true }, { text: "Lymphocytes", isCorrect: false }, { text: "Monocytes", isCorrect: false }, { text: "Eosinophils", isCorrect: false }] },
  { id: "ce-18", text: "What WBC activity indicates immune suppression?", explanation: "Sluggish, minimal WBC movement with no phagocytic activity indicates immune suppression or exhaustion.", answers: [{ text: "Sluggish movement with no phagocytic activity", isCorrect: true }, { text: "Rapid aggressive movement", isCorrect: false }, { text: "Normal motility", isCorrect: false }, { text: "Absence of WBCs", isCorrect: false }] },
  { id: "ce-19", text: "Which WBC type is elevated in parasitic infections?", explanation: "Eosinophils are characteristically elevated in parasitic infections and allergic conditions.", answers: [{ text: "Eosinophils", isCorrect: true }, { text: "Neutrophils", isCorrect: false }, { text: "Basophils", isCorrect: false }, { text: "Monocytes", isCorrect: false }] },
  { id: "ce-20", text: "What can be directly observed about WBC function in LBA?", explanation: "Phagocytic activity — WBCs engulfing debris or organisms — can be observed in real-time in live blood.", answers: [{ text: "Phagocytic activity in real-time", isCorrect: true }, { text: "Antibody production", isCorrect: false }, { text: "DNA synthesis", isCorrect: false }, { text: "Cytokine release", isCorrect: false }] },
  { id: "ce-21", text: "What distinguishes chronic from acute inflammation in LBA?", explanation: "Chronic: sluggish WBCs, debris, persistent fibrin. Acute: hyperactive WBCs, fresh fibrin, increased WBC count.", answers: [{ text: "Chronic: sluggish WBCs/debris; Acute: hyperactive WBCs/fresh fibrin", isCorrect: true }, { text: "No visual difference", isCorrect: false }, { text: "Only cell count differs", isCorrect: false }, { text: "Crystal patterns differ", isCorrect: false }] },
  { id: "ce-22", text: "What does excessive fibrin in plasma indicate?", explanation: "Excessive fibrin strands and networks indicate coagulation cascade activation from liver stress, inflammation, or cardiovascular risk.", answers: [{ text: "Liver stress, inflammation, cardiovascular risk", isCorrect: true }, { text: "Healthy coagulation", isCorrect: false }, { text: "Dehydration only", isCorrect: false }, { text: "Normal finding", isCorrect: false }] },
  { id: "ce-23", text: "What crystal shape indicates gout/uric acid?", explanation: "Needle-shaped (acicular) crystals are characteristic of uric acid / gout.", answers: [{ text: "Needle-shaped", isCorrect: true }, { text: "Plate-shaped", isCorrect: false }, { text: "Cubic", isCorrect: false }, { text: "Spherical", isCorrect: false }] },
  { id: "ce-24", text: "What are chylomicrons and why do they confuse LBA analysis?", explanation: "Chylomicrons are fat globules from recent meals. They cloud plasma and mimic pathological debris, which is why fasting samples are required.", answers: [{ text: "Fat globules from meals that cloud plasma and mimic debris", isCorrect: true }, { text: "White blood cell fragments", isCorrect: false }, { text: "Bacterial colonies", isCorrect: false }, { text: "Mineral deposits", isCorrect: false }] },
  { id: "ce-25", text: "What does background 'snow' in plasma suggest?", explanation: "Particulate debris or 'snow' in plasma indicates toxic burden or digestive insufficiency.", answers: [{ text: "Toxic burden or digestive insufficiency", isCorrect: true }, { text: "Healthy immune activity", isCorrect: false }, { text: "Normal finding", isCorrect: false }, { text: "Equipment malfunction", isCorrect: false }] },
  { id: "ce-26", text: "What is the normal size of platelets?", explanation: "Normal platelets are 2-4 micrometers, the smallest formed elements in blood.", answers: [{ text: "2-4 micrometers", isCorrect: true }, { text: "7-8 micrometers", isCorrect: false }, { text: "10-15 micrometers", isCorrect: false }, { text: "20+ micrometers", isCorrect: false }] },
  { id: "ce-27", text: "What does excessive platelet aggregation indicate?", explanation: "Platelet clumping indicates clotting tendency and cardiovascular risk.", answers: [{ text: "Clotting tendency and cardiovascular risk", isCorrect: true }, { text: "Normal function", isCorrect: false }, { text: "Immune activation", isCorrect: false }, { text: "Nutritional adequacy", isCorrect: false }] },
  { id: "ce-28", text: "What is the oxidative stress LBA pattern?", explanation: "Echinocytes + background debris + fibrin activity = oxidative stress with membrane lipid peroxidation.", answers: [{ text: "Echinocytes + debris + fibrin activity", isCorrect: true }, { text: "Rouleaux only", isCorrect: false }, { text: "Crystal formations", isCorrect: false }, { text: "Clear plasma", isCorrect: false }] },
  { id: "ce-29", text: "What conventional test best correlates with rouleaux?", explanation: "ESR and CRP directly measure the inflammatory proteins that cause rouleaux formation.", answers: [{ text: "ESR and CRP", isCorrect: true }, { text: "Hemoglobin A1c", isCorrect: false }, { text: "TSH", isCorrect: false }, { text: "Vitamin D", isCorrect: false }] },
  { id: "ce-30", text: "Should LBA findings always be correlated with conventional testing?", explanation: "Yes — LBA provides qualitative context that complements quantitative conventional laboratory data.", answers: [{ text: "Yes — always correlate with conventional lab testing", isCorrect: true }, { text: "No — LBA replaces conventional testing", isCorrect: false }, { text: "Only for serious findings", isCorrect: false }, { text: "Only if the patient requests it", isCorrect: false }] },
  { id: "ce-31", text: "What does macrocytosis indicate nutritionally?", explanation: "Enlarged RBCs (>8 micrometers) indicate B12 or folate deficiency, especially with hypersegmented neutrophils.", answers: [{ text: "B12 or folate deficiency", isCorrect: true }, { text: "Iron deficiency", isCorrect: false }, { text: "Zinc deficiency", isCorrect: false }, { text: "Magnesium deficiency", isCorrect: false }] },
  { id: "ce-32", text: "What is the optimal retest interval for standard protocols?", explanation: "Standard protocols are reassessed at 4 weeks to allow interventions time to take effect.", answers: [{ text: "4 weeks", isCorrect: true }, { text: "1 day", isCorrect: false }, { text: "1 year", isCorrect: false }, { text: "6 months", isCorrect: false }] },
  { id: "ce-33", text: "What must be identical for valid before/after comparison?", explanation: "Fasting status, time of day, hydration, and collection technique must be identical.", answers: [{ text: "Fasting status, timing, hydration, and technique", isCorrect: true }, { text: "Only the microscope", isCorrect: false }, { text: "Nothing specific", isCorrect: false }, { text: "Room temperature only", isCorrect: false }] },
  { id: "ce-34", text: "When should a practitioner refer to conventional evaluation?", explanation: "Refer when findings suggest serious disease, symptoms don't improve, or acute conditions require immediate medical attention.", answers: [{ text: "When findings suggest serious disease or symptoms don't improve", isCorrect: true }, { text: "Never", isCorrect: false }, { text: "Only if patient requests", isCorrect: false }, { text: "After every session", isCorrect: false }] },
  { id: "ce-35", text: "What does a declining vitality score indicate?", explanation: "Declining vitality means the current protocol is not effective and should be reassessed.", answers: [{ text: "Protocol is not effective — reassess", isCorrect: true }, { text: "Protocol is working", isCorrect: false }, { text: "Normal fluctuation", isCorrect: false }, { text: "Equipment error", isCorrect: false }] },
  { id: "ce-36", text: "What is the AI confidence threshold requiring manual verification?", explanation: "AI confidence scores below 70% require careful manual verification by the practitioner.", answers: [{ text: "Below 70%", isCorrect: true }, { text: "Below 99%", isCorrect: false }, { text: "Below 50%", isCorrect: false }, { text: "Below 10%", isCorrect: false }] },
  { id: "ce-37", text: "Is AI a replacement for practitioner judgment in LBA?", explanation: "No — AI is a support tool that provides pattern recognition and second opinions, never a replacement for clinical judgment.", answers: [{ text: "No — AI supports but never replaces practitioner judgment", isCorrect: true }, { text: "Yes — AI is always more accurate", isCorrect: false }, { text: "Yes — for routine cases", isCorrect: false }, { text: "Only for beginners", isCorrect: false }] },
  { id: "ce-38", text: "What percentage is required to pass module quizzes?", explanation: "All module quizzes require 80% or higher to pass.", answers: [{ text: "80%", isCorrect: true }, { text: "50%", isCorrect: false }, { text: "70%", isCorrect: false }, { text: "100%", isCorrect: false }] },
  { id: "ce-39", text: "How many modules are in the LBA certification course?", explanation: "The LBA certification course contains 17 comprehensive modules.", answers: [{ text: "17", isCorrect: true }, { text: "10", isCorrect: false }, { text: "5", isCorrect: false }, { text: "25", isCorrect: false }] },
  { id: "ce-40", text: "How many questions are on the certification exam?", explanation: "The LBA certification exam contains 100 multiple-choice questions.", answers: [{ text: "100", isCorrect: true }, { text: "50", isCorrect: false }, { text: "200", isCorrect: false }, { text: "75", isCorrect: false }] },
  { id: "ce-41", text: "How many drops are placed for the dry layer test?", explanation: "8 sequential drops of blood are placed on the slide and allowed to air dry.", answers: [{ text: "8", isCorrect: true }, { text: "1", isCorrect: false }, { text: "3", isCorrect: false }, { text: "20", isCorrect: false }] },
  { id: "ce-42", text: "What do lacunae in dried blood indicate?", explanation: "Clear lacunae (holes) indicate free radical damage disrupting fibrin polymerization — oxidative stress.", answers: [{ text: "Free radical damage and oxidative stress", isCorrect: true }, { text: "Normal drying", isCorrect: false }, { text: "Bacterial contamination", isCorrect: false }, { text: "Excess iron", isCorrect: false }] },
  { id: "ce-43", text: "How many concentric layers does each dried blood drop show?", explanation: "Each dried drop shows 8 concentric layers, each mapped to specific organ systems.", answers: [{ text: "8", isCorrect: true }, { text: "3", isCorrect: false }, { text: "12", isCorrect: false }, { text: "4", isCorrect: false }] },
  { id: "ce-44", text: "What does a normal dry layer pattern look like?", explanation: "Healthy dried blood shows tight, uniform polymerized fibrin mesh with no holes, spots, or disruptions.", answers: [{ text: "Tight, uniform fibrin mesh with no disruptions", isCorrect: true }, { text: "Many holes and dark spots", isCorrect: false }, { text: "Completely clear", isCorrect: false }, { text: "Bright red uniform color", isCorrect: false }] },
  { id: "ce-45", text: "What do dark spots in dry layer testing suggest?", explanation: "Dark concentrated areas correlate with heavy metal toxicity and toxic burden.", answers: [{ text: "Heavy metal toxicity", isCorrect: true }, { text: "Normal variant", isCorrect: false }, { text: "Vitamin deficiency", isCorrect: false }, { text: "Dehydration", isCorrect: false }] },
  { id: "ce-46", text: "Which layers correspond to the cardiovascular/respiratory system?", explanation: "Center layers 1-2 of the dried blood drop map to cardiovascular and respiratory systems.", answers: [{ text: "Layers 1-2 (center)", isCorrect: true }, { text: "Layers 7-8 (periphery)", isCorrect: false }, { text: "Layer 5 only", isCorrect: false }, { text: "All equally", isCorrect: false }] },
  { id: "ce-47", text: "What magnification is used for dry layer analysis?", explanation: "Dry layer analysis uses 40-100x under bright field or phase contrast.", answers: [{ text: "40-100x", isCorrect: true }, { text: "1000x oil immersion", isCorrect: false }, { text: "10x only", isCorrect: false }, { text: "Electron microscopy", isCorrect: false }] },
  { id: "ce-48", text: "How long should drops dry before examination?", explanation: "Drops should air dry 10-15 minutes undisturbed before examination.", answers: [{ text: "10-15 minutes", isCorrect: true }, { text: "1 minute", isCorrect: false }, { text: "1 hour", isCorrect: false }, { text: "Immediately", isCorrect: false }] },
  { id: "ce-49", text: "What three parameters define biological terrain?", explanation: "pH, rH2 (redox potential), and resistivity measured in blood, saliva, and urine.", answers: [{ text: "pH, rH2 (redox potential), resistivity", isCorrect: true }, { text: "Temperature, pressure, volume", isCorrect: false }, { text: "Hemoglobin, hematocrit, platelets", isCorrect: false }, { text: "Glucose, insulin, cortisol", isCorrect: false }] },
  { id: "ce-50", text: "What body fluids are tested in the 9-factor matrix?", explanation: "Blood, saliva, and urine are tested for pH, rH2, and resistivity.", answers: [{ text: "Blood, saliva, urine", isCorrect: true }, { text: "Blood only", isCorrect: false }, { text: "Blood and sweat", isCorrect: false }, { text: "Saliva only", isCorrect: false }] },
  { id: "ce-51", text: "What does elevated rH2 indicate?", explanation: "Elevated rH2 indicates oxidative stress — excess oxidation and free radical activity.", answers: [{ text: "Oxidative stress and free radical excess", isCorrect: true }, { text: "Healthy antioxidant status", isCorrect: false }, { text: "Alkalosis", isCorrect: false }, { text: "Dehydration", isCorrect: false }] },
  { id: "ce-52", text: "What is the normal blood pH range?", explanation: "Blood pH is tightly regulated between 7.35-7.45.", answers: [{ text: "7.35-7.45", isCorrect: true }, { text: "6.0-6.5", isCorrect: false }, { text: "8.0-8.5", isCorrect: false }, { text: "5.0-5.5", isCorrect: false }] },
  { id: "ce-53", text: "What does acidic terrain promote in the pleomorphic framework?", explanation: "Acidic terrain promotes upward microbial development from symbiotic toward parasitic/fungal forms.", answers: [{ text: "Upward microbial development toward parasitic/fungal forms", isCorrect: true }, { text: "Improved health", isCorrect: false }, { text: "Reduced inflammation", isCorrect: false }, { text: "Better immune function", isCorrect: false }] },
  { id: "ce-54", text: "What does low resistivity indicate?", explanation: "Low resistivity means too many dissolved minerals/metals — mineral excess or toxic metal burden.", answers: [{ text: "Mineral excess or toxic metal burden", isCorrect: true }, { text: "Mineral deficiency", isCorrect: false }, { text: "Normal status", isCorrect: false }, { text: "Dehydration", isCorrect: false }] },
  { id: "ce-55", text: "Who developed the quantifiable terrain assessment system?", explanation: "Professor Louis-Claude Vincent developed the Bio-Electronic Vincent (BEV) system.", answers: [{ text: "Louis-Claude Vincent", isCorrect: true }, { text: "Enderlein", isCorrect: false }, { text: "Bechamp", isCorrect: false }, { text: "Pasteur", isCorrect: false }] },
  { id: "ce-56", text: "What is the optimal blood rH2 range?", explanation: "Optimal blood rH2 is 21-23, indicating balanced redox status.", answers: [{ text: "21-23", isCorrect: true }, { text: "0-5", isCorrect: false }, { text: "35-42", isCorrect: false }, { text: "7-8", isCorrect: false }] },
  { id: "ce-57", text: "What is the fundamental unit in Enderlein's cyclogeny?", explanation: "The protit — the smallest living protein colloidal particle — is the base of all development.", answers: [{ text: "Protit", isCorrect: true }, { text: "Cell", isCorrect: false }, { text: "Gene", isCorrect: false }, { text: "Virus", isCorrect: false }] },
  { id: "ce-58", text: "What does 'upward development' mean in cyclogeny?", explanation: "Pathological progression from harmless protits through bacterial stages to fungal culmination.", answers: [{ text: "Pathological progression from protit to fungus", isCorrect: true }, { text: "Growth in cell size", isCorrect: false }, { text: "Improved health", isCorrect: false }, { text: "Cell division", isCorrect: false }] },
  { id: "ce-59", text: "What determines the direction of cyclogeny development?", explanation: "Biological terrain (pH, redox, minerals) determines whether development goes upward (pathological) or downward (therapeutic).", answers: [{ text: "Biological terrain (pH, redox, minerals)", isCorrect: true }, { text: "Genetics alone", isCorrect: false }, { text: "Random chance", isCorrect: false }, { text: "External infection", isCorrect: false }] },
  { id: "ce-60", text: "What are the two primary endobiont cycles?", explanation: "Mucor racemosus (vascular/coagulation) and Aspergillus niger (skeletal/mineral).", answers: [{ text: "Mucor racemosus and Aspergillus niger", isCorrect: true }, { text: "E. coli and Staph", isCorrect: false }, { text: "Candida and Strep", isCorrect: false }, { text: "Salmonella and Listeria", isCorrect: false }] },
  { id: "ce-61", text: "What is isopathic therapy?", explanation: "Using preparations from the same organism cycle to push organisms back downward toward the harmless protit phase.", answers: [{ text: "Using preparations from the organism's cycle to reverse development", isCorrect: true }, { text: "Using antibiotics", isCorrect: false }, { text: "Surgery", isCorrect: false }, { text: "Vaccination", isCorrect: false }] },
  { id: "ce-62", text: "What is the therapeutic goal regarding cyclogeny?", explanation: "Downward development — restoring organisms to the harmless, symbiotic protit phase.", answers: [{ text: "Downward development to symbiotic protit phase", isCorrect: true }, { text: "Upward development", isCorrect: false }, { text: "Complete organism elimination", isCorrect: false }, { text: "Stabilization at bacterial phase", isCorrect: false }] },
  { id: "ce-63", text: "What are chondrites in cyclogeny?", explanation: "Thread-like formations representing an intermediate stage between protits and bacterial forms.", answers: [{ text: "Thread-like intermediate developmental forms", isCorrect: true }, { text: "Crystal formations", isCorrect: false }, { text: "A type of mineral", isCorrect: false }, { text: "White blood cells", isCorrect: false }] },
  { id: "ce-64", text: "What system does Mucor racemosus primarily affect?", explanation: "Mucor racemosus cycle primarily affects blood coagulation and the vascular system.", answers: [{ text: "Coagulation and vascular system", isCorrect: true }, { text: "Skeletal system", isCorrect: false }, { text: "Nervous system", isCorrect: false }, { text: "Respiratory system", isCorrect: false }] },
  { id: "ce-65", text: "What system does Aspergillus niger primarily affect?", explanation: "Aspergillus niger cycle primarily affects calcium metabolism and the skeletal system.", answers: [{ text: "Calcium metabolism and skeletal system", isCorrect: true }, { text: "Coagulation system", isCorrect: false }, { text: "Digestive system", isCorrect: false }, { text: "Immune system", isCorrect: false }] },
  { id: "ce-66", text: "What is the endobiont progression?", explanation: "Symbiont (helpful) → parasite (disruptive) → fungus (pathological).", answers: [{ text: "Symbiont → parasite → fungus", isCorrect: true }, { text: "Fungus → bacteria → virus", isCorrect: false }, { text: "Parasite → symbiont → fungus", isCorrect: false }, { text: "Random sequence", isCorrect: false }] },
  { id: "ce-67", text: "What isopathic remedy addresses the Mucor racemosus cycle?", explanation: "Mucokehl is specific to the Mucor racemosus endobiont cycle.", answers: [{ text: "Mucokehl", isCorrect: true }, { text: "Nigersan", isCorrect: false }, { text: "Penicillin", isCorrect: false }, { text: "Aspirin", isCorrect: false }] },
  { id: "ce-68", text: "What isopathic remedy addresses the Aspergillus niger cycle?", explanation: "Nigersan is specific to the Aspergillus niger endobiont cycle.", answers: [{ text: "Nigersan", isCorrect: true }, { text: "Mucokehl", isCorrect: false }, { text: "Fluconazole", isCorrect: false }, { text: "Nystatin", isCorrect: false }] },
  { id: "ce-69", text: "Can the endobiont ever be completely eliminated?", explanation: "No — per Enderlein, endobionts exist permanently at the protit level in all blood. Treatment shifts them downward.", answers: [{ text: "No — they exist permanently; treatment shifts them to symbiotic phase", isCorrect: true }, { text: "Yes — with antibiotics", isCorrect: false }, { text: "Yes — with surgery", isCorrect: false }, { text: "Yes — with antifungals", isCorrect: false }] },
  { id: "ce-70", text: "What is zeta potential?", explanation: "The electrical potential on blood cell surfaces that maintains colloidal suspension and keeps cells dispersed.", answers: [{ text: "Electrical potential maintaining blood cell colloidal suspension", isCorrect: true }, { text: "Blood pressure measurement", isCorrect: false }, { text: "Oxygen saturation", isCorrect: false }, { text: "Temperature", isCorrect: false }] },
  { id: "ce-71", text: "What charge do healthy blood cells carry?", explanation: "Healthy cells carry negative surface charge (from sialic acid) that creates repulsion between cells.", answers: [{ text: "Negative charge", isCorrect: true }, { text: "Positive charge", isCorrect: false }, { text: "Neutral", isCorrect: false }, { text: "Variable", isCorrect: false }] },
  { id: "ce-72", text: "What happens when zeta potential decreases?", explanation: "Reduced zeta potential means less cell-to-cell repulsion, leading to aggregation, rouleaux, and sludging.", answers: [{ text: "Cells aggregate into rouleaux and sludging", isCorrect: true }, { text: "Cells spread apart", isCorrect: false }, { text: "Blood becomes thinner", isCorrect: false }, { text: "Nothing changes", isCorrect: false }] },
  { id: "ce-73", text: "Which minerals reduce zeta potential?", explanation: "Cationic minerals: aluminum, excess iron, excess calcium overwhelm the negative surface charge.", answers: [{ text: "Aluminum, excess iron, excess calcium", isCorrect: true }, { text: "Potassium and magnesium", isCorrect: false }, { text: "Sodium chloride", isCorrect: false }, { text: "All minerals equally", isCorrect: false }] },
  { id: "ce-74", text: "What improves zeta potential?", explanation: "Hydration, alkaline minerals (K, Mg), essential fatty acids, and antioxidants.", answers: [{ text: "Hydration, alkaline minerals, EFAs, antioxidants", isCorrect: true }, { text: "Dehydration", isCorrect: false }, { text: "Heavy metals", isCorrect: false }, { text: "Acidic foods", isCorrect: false }] },
  { id: "ce-75", text: "How is zeta potential graded in LBA?", explanation: "Grade 0 (none) to Grade 4 (near-complete aggregation) based on severity of RBC aggregation.", answers: [{ text: "Grade 0-4 based on aggregation severity", isCorrect: true }, { text: "Voltmeter measurement", isCorrect: false }, { text: "Blood pressure correlation", isCorrect: false }, { text: "Color assessment", isCorrect: false }] },
  { id: "ce-76", text: "What cardiovascular risk does poor zeta potential indicate?", explanation: "Increased blood viscosity and sludging correlate with atherosclerosis, stroke, and cardiovascular disease.", answers: [{ text: "Atherosclerosis, stroke, cardiovascular disease", isCorrect: true }, { text: "No cardiovascular risk", isCorrect: false }, { text: "Only bone problems", isCorrect: false }, { text: "Heart valve issues only", isCorrect: false }] },
  { id: "ce-77", text: "Which parasite shows Maltese cross tetrads?", explanation: "Babesia shows pathognomonic Maltese cross (tetrad) formations within RBCs.", answers: [{ text: "Babesia", isCorrect: true }, { text: "Malaria", isCorrect: false }, { text: "Trypanosoma", isCorrect: false }, { text: "Borrelia", isCorrect: false }] },
  { id: "ce-78", text: "What shape does Borrelia show in dark field?", explanation: "Borrelia spirochetes show characteristic corkscrew/helical shape with undulating motility.", answers: [{ text: "Corkscrew/helical with undulating motility", isCorrect: true }, { text: "Round spheres", isCorrect: false }, { text: "Square blocks", isCorrect: false }, { text: "Flat discs", isCorrect: false }] },
  { id: "ce-79", text: "Should parasitic findings in LBA be confirmed conventionally?", explanation: "Yes — significant parasitic findings should always be confirmed with conventional parasitology testing.", answers: [{ text: "Yes — always confirm with conventional testing", isCorrect: true }, { text: "No — LBA is sufficient", isCorrect: false }, { text: "Only for malaria", isCorrect: false }, { text: "Only in tropical regions", isCorrect: false }] },
  { id: "ce-80", text: "What does the pleomorphic perspective add to parasitology?", explanation: "It extends parasitism to include endobiont organisms shifting from symbiotic to parasitic behavior based on terrain.", answers: [{ text: "Endobionts can shift from symbiotic to parasitic based on terrain", isCorrect: true }, { text: "Nothing additional", isCorrect: false }, { text: "Only external parasites matter", isCorrect: false }, { text: "Parasites don't exist", isCorrect: false }] },
  { id: "ce-81", text: "How should LBA be presented within the PMA framework?", explanation: "As an educational assessment tool, not medical diagnosis.", answers: [{ text: "As an educational assessment tool, not medical diagnosis", isCorrect: true }, { text: "As a replacement for medical testing", isCorrect: false }, { text: "As a diagnostic procedure", isCorrect: false }, { text: "As a treatment modality", isCorrect: false }] },
  { id: "ce-82", text: "What language should be used in LBA reports?", explanation: "Observation language (observations suggest) not diagnostic language (diagnosis shows).", answers: [{ text: "Observation language, not diagnostic language", isCorrect: true }, { text: "Medical diagnostic terminology", isCorrect: false }, { text: "Legal terminology", isCorrect: false }, { text: "Any language", isCorrect: false }] },
  { id: "ce-83", text: "What must be obtained before every LBA session?", explanation: "Member consent including understanding of LBA's educational nature.", answers: [{ text: "Member consent with understanding of LBA's educational nature", isCorrect: true }, { text: "Insurance authorization", isCorrect: false }, { text: "Medical referral", isCorrect: false }, { text: "Nothing required", isCorrect: false }] },
  { id: "ce-84", text: "What data standard must LBA records comply with?", explanation: "HIPAA-compliant storage with proper security for all member images and records.", answers: [{ text: "HIPAA-compliant storage", isCorrect: true }, { text: "No requirements", isCorrect: false }, { text: "Public cloud only", isCorrect: false }, { text: "Paper only", isCorrect: false }] },
  { id: "ce-85", text: "What should practitioners never claim about LBA?", explanation: "Never claim to diagnose, treat, cure, or prevent any disease.", answers: [{ text: "To diagnose, treat, cure, or prevent disease", isCorrect: true }, { text: "To provide educational assessment", isCorrect: false }, { text: "To show visual findings", isCorrect: false }, { text: "To complement testing", isCorrect: false }] },
  { id: "ce-86", text: "What annual CE requirement maintains certification?", explanation: "10 hours of continuing education per year.", answers: [{ text: "10 hours", isCorrect: true }, { text: "None", isCorrect: false }, { text: "100 hours", isCorrect: false }, { text: "Full re-exam", isCorrect: false }] },
  { id: "ce-87", text: "What oil type is used for dark field oil immersion?", explanation: "Type A immersion oil is specifically designed for dark field microscopy.", answers: [{ text: "Type A immersion oil", isCorrect: true }, { text: "Mineral oil", isCorrect: false }, { text: "Olive oil", isCorrect: false }, { text: "Any oil", isCorrect: false }] },
  { id: "ce-88", text: "What lancet depth is recommended for LBA?", explanation: "2.4mm sterile lancet for finger prick collection.", answers: [{ text: "2.4mm", isCorrect: true }, { text: "0.5mm", isCorrect: false }, { text: "5mm", isCorrect: false }, { text: "10mm", isCorrect: false }] },
  { id: "ce-89", text: "At what angle should the coverslip be applied?", explanation: "45-degree angle prevents air bubbles from being trapped.", answers: [{ text: "45 degrees", isCorrect: true }, { text: "90 degrees", isCorrect: false }, { text: "0 degrees (flat)", isCorrect: false }, { text: "10 degrees", isCorrect: false }] },
  { id: "ce-90", text: "What artifact does residual alcohol cause?", explanation: "Alcohol not fully dried creates echinocyte artifacts.", answers: [{ text: "Echinocyte artifact", isCorrect: true }, { text: "Rouleaux artifact", isCorrect: false }, { text: "Hemolysis", isCorrect: false }, { text: "Crystal formation", isCorrect: false }] },
  { id: "ce-91", text: "What Zone assesses dynamic changes and vitality?", explanation: "Zone 5 (Dynamic Assessment) evaluates movement, activity, time-lapse changes, and vitality scoring.", answers: [{ text: "Zone 5 — Dynamic Assessment", isCorrect: true }, { text: "Zone 1 — Center Field", isCorrect: false }, { text: "Zone 3 — Plasma Quality", isCorrect: false }, { text: "Zone 2 — Peripheral Scan", isCorrect: false }] },
  { id: "ce-92", text: "What proteolytic enzymes address excessive fibrin?", explanation: "Nattokinase, serrapeptase, and bromelain are proteolytic enzymes that break down excess fibrin.", answers: [{ text: "Nattokinase, serrapeptase, bromelain", isCorrect: true }, { text: "Vitamin C only", isCorrect: false }, { text: "Iron supplements", isCorrect: false }, { text: "Calcium supplements", isCorrect: false }] },
  { id: "ce-93", text: "What does RBC membrane stiffness indicate?", explanation: "Stiff membranes indicate oxidative damage to the lipid bilayer, reducing flexibility and oxygen delivery.", answers: [{ text: "Oxidative damage to membrane lipid bilayer", isCorrect: true }, { text: "Normal aging", isCorrect: false }, { text: "Healthy membranes", isCorrect: false }, { text: "Iron overload", isCorrect: false }] },
  { id: "ce-94", text: "What WBC becomes a tissue macrophage?", explanation: "Monocytes leave the bloodstream and become macrophages in tissues.", answers: [{ text: "Monocyte", isCorrect: true }, { text: "Neutrophil", isCorrect: false }, { text: "Lymphocyte", isCorrect: false }, { text: "Eosinophil", isCorrect: false }] },
  { id: "ce-95", text: "What layers correspond to immune/lymphatic in dry layer?", explanation: "Layer 7 maps to the immune/lymphatic system.", answers: [{ text: "Layer 7", isCorrect: true }, { text: "Layer 1", isCorrect: false }, { text: "Layer 4", isCorrect: false }, { text: "Layer 8", isCorrect: false }] },
  { id: "ce-96", text: "What terrain correlates with echinocytes?", explanation: "Acidic + oxidized terrain (low pH + high rH2) correlates with echinocyte formation.", answers: [{ text: "Acidic + oxidized (low pH + high rH2)", isCorrect: true }, { text: "Alkaline + reduced", isCorrect: false }, { text: "Normal terrain", isCorrect: false }, { text: "Any terrain", isCorrect: false }] },
  { id: "ce-97", text: "What characterizes P. falciparum gametocytes?", explanation: "P. falciparum gametocytes have a distinctive banana/crescent shape.", answers: [{ text: "Banana/crescent shape", isCorrect: true }, { text: "Round shape", isCorrect: false }, { text: "Square shape", isCorrect: false }, { text: "Star shape", isCorrect: false }] },
  { id: "ce-98", text: "What is the PMA legal protection based on?", explanation: "Member-to-member private contracts and constitutional rights to private association.", answers: [{ text: "Private contracts and constitutional association rights", isCorrect: true }, { text: "Medical licensing", isCorrect: false }, { text: "Insurance coverage", isCorrect: false }, { text: "Government approval", isCorrect: false }] },
  { id: "ce-99", text: "What replaces 'prescription' in PMA context?", explanation: "Use 'educational suggestion' instead of 'prescription'.", answers: [{ text: "Educational suggestion", isCorrect: true }, { text: "Medical order", isCorrect: false }, { text: "Treatment plan", isCorrect: false }, { text: "Directive", isCorrect: false }] },
  { id: "ce-100", text: "What is the maximum number of certification exam attempts?", explanation: "The certification exam allows a maximum of 3 attempts.", answers: [{ text: "3", isCorrect: true }, { text: "1", isCorrect: false }, { text: "5", isCorrect: false }, { text: "Unlimited", isCorrect: false }] },
];

export async function seedLBACertificationExam(): Promise<void> {
  console.log("[LBA Cert Exam] Seeding 100-question certification exam...");

  const questionIds = CERT_EXAM_QUESTIONS.map(q => q.id);
  try {
    if (questionIds.length > 0) {
      await db.delete(quizAnswers).where(inArray(quizAnswers.questionId, questionIds));
    }
    await db.delete(quizQuestions).where(eq(quizQuestions.quizId, CERT_EXAM_ID));
    await db.delete(quizzes).where(eq(quizzes.id, CERT_EXAM_ID));
    console.log("[LBA Cert Exam] Cleaned existing exam data");
  } catch (e: any) {
    console.log("[LBA Cert Exam] Cleanup note:", e.message?.substring(0, 100));
  }

  try {
    await db.insert(quizzes).values({
      id: CERT_EXAM_ID,
      title: "FFPMA LBA Practitioner Certification Examination",
      slug: "lba-certification-exam",
      description: "100-question comprehensive examination covering all 17 modules of the LBA Practitioner Certification course. Passing score: 80%. Maximum 3 attempts. 2-hour time limit.",
      difficulty: "advanced",
      passingScore: 80,
      maxAttempts: 3,
      timeLimit: 120,
      questionsCount: 100,
      isActive: true,
      requiresMembership: true,
    }).onConflictDoNothing();
    console.log("[LBA Cert Exam] Created certification exam quiz");

    for (const q of CERT_EXAM_QUESTIONS) {
      await db.insert(quizQuestions).values({
        id: q.id,
        quizId: CERT_EXAM_ID,
        questionText: q.text,
        questionType: "multiple_choice",
        explanation: q.explanation,
        sortOrder: CERT_EXAM_QUESTIONS.indexOf(q) + 1,
        points: 1,
        isActive: true,
      }).onConflictDoNothing();

      for (let a = 0; a < q.answers.length; a++) {
        await db.insert(quizAnswers).values({
          questionId: q.id,
          answerText: q.answers[a].text,
          isCorrect: q.answers[a].isCorrect,
          sortOrder: a + 1,
        }).onConflictDoNothing();
      }
    }
    console.log("[LBA Cert Exam] Seeded 100 certification exam questions with answers");
  } catch (e: any) {
    console.log("[LBA Cert Exam] Certification exam may already exist:", e.message?.substring(0, 80));
  }
}
