import { storage } from "../storage";
import { db } from "../db";
import { eq } from "drizzle-orm";
import { bloodSamples } from "@shared/schema";
import type { InsertBloodSample } from "@shared/schema";

interface BloodSampleSeedData extends InsertBloodSample {
  tags: string[];
}

const lbaBloodSampleData: BloodSampleSeedData[] = [
  {
    title: "Protits (Colloid Albumin Formations)",
    scientificName: "Enderlein Protit",
    commonName: "Protits, Colloid albumin bodies",
    organismType: "blood_cell_morphology",
    category: "morphology",
    description: "Protits are the smallest living units according to Enderlein's cyclogeny theory. They appear as tiny, motile colloidal protein particles in the blood plasma visible under dark field microscopy. In healthy blood, protits exist in symbiotic form and are considered the foundational stage of all microbial life cycles.",
    clinicalSignificance: "Protits represent the base of Enderlein's cyclogeny. Their presence in normal, non-aggregated form indicates healthy biological terrain. Aggregation or increased activity of protits suggests terrain disturbance and the beginning of upward microbial development toward parasitic forms.",
    diagnosticCriteria: "Dark field microscopy reveals tiny (0.01-0.1 micrometer), highly motile, luminescent particles in plasma. They exhibit Brownian-type movement but with apparent directional motility. Increased aggregation or clustering of protits indicates terrain shift.",
    differentialDiagnosis: "Protein precipitates, lipid particles, platelet microparticles, cellular debris",
    magnification: "1000x",
    stainType: "dark_field",
    sampleType: "whole blood",
    morphologyDescription: "Extremely small, bright, luminescent particles visible as points of light against the dark field background. They demonstrate active motility. When terrain is disturbed, protits aggregate into larger formations resembling spermatid-like bodies.",
    sizeRange: "0.01-0.1 micrometers",
    shapeCharacteristics: "Point-like to spherical, may form aggregates",
    colorCharacteristics: "Bright white luminescence in dark field",
    associatedConditions: ["Normal symbiotic balance (when dispersed)", "Terrain disturbance (when aggregating)", "Early cyclogeny activation"],
    symptoms: ["None when in symbiotic state", "Non-specific symptoms when terrain shifts begin"],
    transmissionRoute: null,
    prevalence: "Present in all living blood",
    identificationKeywords: ["protit", "colloid", "albumin", "Enderlein", "cyclogeny", "pleomorphism"],
    aiPromptContext: "When analyzing for protits: These are the smallest units in Enderlein's cyclogeny. In dark field, look for tiny bright motile particles in plasma. Normal: dispersed, individual particles. Concerning: aggregation into clusters or chains suggesting terrain shift and beginning of upward development cycle.",
    confidenceFactors: "Dark field visualization, motility pattern, aggregation state, terrain assessment correlation",
    sourceCitation: "Dumrese/Haefeli - Dark Field Microscopy: Pleomorphism",
    isFeatured: true,
    sortOrder: 100,
    tags: ["pleomorphism", "cyclogeny", "Enderlein", "dark-field", "protit", "terrain"]
  },
  {
    title: "Spermatids (Primary Cell Formations)",
    scientificName: "Enderlein Spermit",
    commonName: "Spermatids, Primary cells",
    organismType: "blood_cell_morphology",
    category: "morphology",
    description: "Spermatids are early developmental forms in Enderlein's cyclogeny arising from protit aggregation. They appear as elongated or tadpole-shaped formations in blood plasma under dark field microscopy, representing the first morphological stage above protits in the upward development cycle.",
    clinicalSignificance: "The presence of spermatids in blood indicates that protits have begun aggregating and the cyclogeny is progressing. This is an early indicator of terrain disturbance and the body's internal environment shifting toward conditions that support parasitic microbial development.",
    diagnosticCriteria: "Dark field microscopy shows elongated, motile formations larger than protits but smaller than bacterial forms. They may have a head-and-tail morphology resembling spermatozoa. Their presence in increased numbers correlates with terrain imbalance.",
    differentialDiagnosis: "Actual spermatozoa (if present), fibrin strands, platelet aggregates",
    magnification: "1000x",
    stainType: "dark_field",
    sampleType: "whole blood",
    morphologyDescription: "Elongated formations with a denser head region and thinner tail-like extension. Bright in dark field. Active motility. May appear individually or in small groups. Size intermediate between protits and bacterial forms.",
    sizeRange: "0.5-2 micrometers",
    shapeCharacteristics: "Tadpole or elongated oval with tail",
    colorCharacteristics: "Bright white in dark field",
    associatedConditions: ["Biological terrain disturbance", "Early cyclogeny activation", "pH imbalance", "Oxidative stress onset"],
    symptoms: ["Fatigue", "General malaise", "Digestive disturbance"],
    transmissionRoute: null,
    prevalence: "Common in terrain-disturbed blood",
    identificationKeywords: ["spermatid", "spermit", "primary cell", "cyclogeny", "pleomorphism", "Enderlein"],
    aiPromptContext: "When analyzing for spermatids: Look for elongated tadpole-shaped bright formations in dark field plasma. These indicate early upward cyclogeny development from protit aggregation. Correlate with terrain markers (pH, rH2, resistivity) for full assessment.",
    confidenceFactors: "Morphology consistent with spermatid forms, motility pattern, terrain assessment",
    sourceCitation: "Dumrese/Haefeli - Dark Field Microscopy: Pleomorphism",
    sortOrder: 101,
    tags: ["pleomorphism", "cyclogeny", "Enderlein", "dark-field", "spermatid", "terrain"]
  },
  {
    title: "Chondrites (Thread Formations)",
    scientificName: "Enderlein Chondrit",
    commonName: "Chondrites, Thread forms",
    organismType: "blood_cell_morphology",
    category: "morphology",
    description: "Chondrites are thread-like or filamentous formations representing an intermediate developmental stage in Enderlein's cyclogeny. They appear as fine, elongated threads in blood plasma visible under dark field microscopy, indicating progression from spermatid-level development toward more complex bacterial forms.",
    clinicalSignificance: "Chondrites indicate advancing cyclogeny beyond the spermatid stage. Their presence in significant numbers suggests the biological terrain has deteriorated sufficiently to support more complex microbial forms. This correlates with increased inflammatory burden and acidic terrain conditions.",
    diagnosticCriteria: "Dark field microscopy reveals fine, thread-like formations in plasma that may be straight, curved, or branching. They are thinner than typical bacterial rods and may show subtle motility. Distinguished from fibrin strands by their uniformity and behavior.",
    differentialDiagnosis: "Fibrin strands, collagen fibers, filamentous bacteria",
    magnification: "1000x",
    stainType: "dark_field",
    sampleType: "whole blood",
    morphologyDescription: "Fine, thread-like formations of uniform diameter. May appear as straight, curved, or gently undulating filaments. Bright against dark field background. Can occur individually or in loose networks. More defined structure than fibrin spicules.",
    sizeRange: "2-10 micrometers length, sub-micrometer width",
    shapeCharacteristics: "Linear filaments, may curve or branch",
    colorCharacteristics: "Bright white threads in dark field",
    associatedConditions: ["Advancing terrain disturbance", "Chronic inflammation", "Acidosis", "Immune dysregulation"],
    symptoms: ["Chronic fatigue", "Recurrent infections", "Digestive dysfunction", "Joint pain"],
    transmissionRoute: null,
    prevalence: "Common in chronically ill individuals",
    identificationKeywords: ["chondrite", "thread", "filament", "cyclogeny", "pleomorphism", "Enderlein"],
    aiPromptContext: "When analyzing for chondrites: Look for fine thread-like formations in dark field plasma. Distinguish from fibrin by their uniform diameter and behavior. Chondrites indicate mid-level cyclogeny progression. Correlate with patient symptoms and terrain assessment.",
    confidenceFactors: "Thread morphology, uniform diameter, dark field characteristics, terrain correlation",
    sourceCitation: "Dumrese/Haefeli - Dark Field Microscopy: Pleomorphism",
    sortOrder: 102,
    tags: ["pleomorphism", "cyclogeny", "Enderlein", "dark-field", "chondrite", "filament"]
  },
  {
    title: "Dioecotecitas (Branching Filamentous Forms)",
    scientificName: "Enderlein Dioecothecit",
    commonName: "Dioecotecitas, Branching forms",
    organismType: "blood_cell_morphology",
    category: "morphology",
    description: "Dioecotecitas are branching filamentous forms representing an advanced stage in Enderlein's cyclogeny. They demonstrate more complex morphological organization than chondrites, with distinct branching patterns visible under dark field microscopy.",
    clinicalSignificance: "The presence of dioecotecitas indicates significant progression of the upward development cycle, suggesting substantially disturbed biological terrain. Their appearance correlates with chronic conditions and significant immune compromise or inflammatory burden.",
    diagnosticCriteria: "Dark field microscopy reveals branching filamentous structures with Y-shaped or tree-like branching patterns. More complex organization than simple chondrites. May show areas of thickening at branch points.",
    differentialDiagnosis: "Fungal hyphae, fibrin networks, branching bacteria (Actinomyces)",
    magnification: "1000x",
    stainType: "dark_field",
    sampleType: "whole blood",
    morphologyDescription: "Branching filamentous structures with distinct Y-shaped or dichotomous branching. More substantial than chondrites. Branch points may show nodular thickening. Formations suggest organizational complexity approaching fungal morphology.",
    sizeRange: "5-20 micrometers total extent",
    shapeCharacteristics: "Branching filaments with Y-shaped divisions",
    colorCharacteristics: "Bright branching structures in dark field",
    associatedConditions: ["Advanced terrain disturbance", "Chronic degenerative conditions", "Fungal overgrowth tendency", "Severe pH imbalance"],
    symptoms: ["Chronic illness", "Autoimmune tendencies", "Severe fatigue", "Multiple system dysfunction"],
    transmissionRoute: null,
    prevalence: "Less common, indicates advanced pathology",
    identificationKeywords: ["dioecotecita", "branching", "filament", "cyclogeny", "pleomorphism"],
    aiPromptContext: "When analyzing for dioecotecitas: Look for branching filamentous structures in dark field. These represent advanced cyclogeny progression toward fungal forms. Distinguish from true fungal hyphae by size and clinical context. Indicates significant terrain disturbance requiring comprehensive intervention.",
    confidenceFactors: "Branching morphology, clinical context, terrain assessment, cyclogeny stage correlation",
    sourceCitation: "Dumrese/Haefeli - Dark Field Microscopy: Pleomorphism",
    sortOrder: 103,
    tags: ["pleomorphism", "cyclogeny", "Enderlein", "dark-field", "dioecotecita", "branching"]
  },
  {
    title: "Tecitas (Type I, II, III Structural Forms)",
    scientificName: "Enderlein Thecit",
    commonName: "Tecitas, Envelope forms",
    organismType: "blood_cell_morphology",
    category: "morphology",
    description: "Tecitas are progressive structural organizations in Enderlein's upward development cycle, classified into three types (I, II, III) representing increasing complexity. They are characterized by membrane-enclosed formations containing internal structures, visible under dark field microscopy.",
    clinicalSignificance: "Tecitas represent a transition toward higher organizational complexity in the cyclogeny. Type I shows simple encapsulation, Type II demonstrates internal differentiation, and Type III approaches primitive cellular organization. Their presence indicates advanced terrain disturbance.",
    diagnosticCriteria: "Dark field microscopy reveals enclosed formations with visible membrane boundaries. Type I: simple enclosed spheres. Type II: enclosed forms with internal granulation. Type III: complex enclosed forms with organized internal structures approaching cellular morphology.",
    differentialDiagnosis: "White blood cell fragments, apoptotic bodies, microvesicles",
    magnification: "1000x",
    stainType: "dark_field",
    sampleType: "whole blood",
    morphologyDescription: "Spherical to ovoid formations with distinct membrane boundaries. Internal contents vary by type: Type I clear to granular, Type II shows distinct internal particles, Type III has organized sub-structures. Bright peripheral membrane in dark field.",
    sizeRange: "1-5 micrometers",
    shapeCharacteristics: "Spherical to ovoid, membrane-enclosed",
    colorCharacteristics: "Bright membrane outline with variable internal density in dark field",
    associatedConditions: ["Progressive terrain disturbance", "Transition toward parasitic/fungal development", "Chronic immune challenge"],
    symptoms: ["Progressive chronic illness", "Treatment resistance", "Multi-system involvement"],
    transmissionRoute: null,
    prevalence: "Uncommon, indicates progressive cyclogeny",
    identificationKeywords: ["tecita", "thecit", "envelope", "cyclogeny", "pleomorphism", "Enderlein"],
    aiPromptContext: "When analyzing for tecitas: Look for membrane-enclosed spherical formations in dark field. Classify by internal complexity (Type I simple, II granular, III organized). These represent advanced cyclogeny stages requiring aggressive terrain correction.",
    confidenceFactors: "Membrane-enclosed morphology, internal complexity, cyclogeny staging",
    sourceCitation: "Dumrese/Haefeli - Dark Field Microscopy: Pleomorphism",
    sortOrder: 104,
    tags: ["pleomorphism", "cyclogeny", "Enderlein", "dark-field", "tecita", "envelope"]
  },
  {
    title: "Cistaces (Encapsulated Higher Forms)",
    scientificName: "Enderlein Cystit",
    commonName: "Cistaces, Cyst forms",
    organismType: "blood_cell_morphology",
    category: "morphology",
    description: "Cistaces are encapsulated forms representing a higher organizational stage in Enderlein's cyclogeny. They appear as thick-walled, rounded formations containing dense internal material, visible under dark field and phase contrast microscopy. They represent a dormant or resistant stage in the developmental cycle.",
    clinicalSignificance: "Cistaces indicate that the upward development has reached a stage where organisms are forming resistant, encapsulated structures. This suggests deeply entrenched terrain disturbance and chronic pathological conditions that have persisted long enough for organisms to develop protective encapsulation.",
    diagnosticCriteria: "Dark field microscopy reveals thick-walled, rounded formations with dense internal content. The wall appears as a bright ring in dark field. Internal contents may be homogeneous or granular. Size larger than typical bacteria but smaller than most blood cells.",
    differentialDiagnosis: "Bacterial spores, encysted parasites, cellular inclusions, lipid droplets",
    magnification: "1000x",
    stainType: "dark_field",
    sampleType: "whole blood",
    morphologyDescription: "Thick-walled, rounded to spherical formations with bright peripheral wall in dark field. Dense internal content that may show granular or structured appearance. May occur individually or in small clusters. Resistant to environmental changes.",
    sizeRange: "2-8 micrometers",
    shapeCharacteristics: "Spherical, thick-walled, encapsulated",
    colorCharacteristics: "Bright thick wall with dense internal content in dark field",
    associatedConditions: ["Chronic terrain disturbance", "Treatment-resistant conditions", "Deep mycotic involvement", "Advanced cyclogeny"],
    symptoms: ["Chronic treatment-resistant illness", "Cyclical symptom patterns", "Deep immune dysfunction"],
    transmissionRoute: null,
    prevalence: "Rare, indicates advanced pathology",
    identificationKeywords: ["cistace", "cystit", "cyst", "encapsulated", "cyclogeny", "pleomorphism"],
    aiPromptContext: "When analyzing for cistaces: Look for thick-walled spherical formations in dark field. These represent resistant stages in advanced cyclogeny. Their presence indicates deeply entrenched terrain disturbance requiring intensive, prolonged intervention protocols.",
    confidenceFactors: "Thick-walled morphology, size range, clinical context",
    sourceCitation: "Dumrese/Haefeli - Dark Field Microscopy: Pleomorphism",
    sortOrder: 105,
    tags: ["pleomorphism", "cyclogeny", "Enderlein", "dark-field", "cistace", "encapsulated"]
  },
  {
    title: "Rod Forms (Bacterial Phase - Cyclogeny)",
    scientificName: "Enderlein Stabchenform",
    commonName: "Rod forms, Bacterial rods",
    organismType: "bacteria",
    category: "morphology",
    description: "Rod forms in the context of Enderlein's cyclogeny represent bacterial-phase morphologies that have developed from earlier pleomorphic stages. These are elongated, rod-shaped forms visible in dark field microscopy that indicate the cyclogeny has progressed to true bacterial morphology.",
    clinicalSignificance: "Rod forms represent a critical stage in the cyclogeny where the upward development has reached true bacterial morphology. This indicates significant terrain disturbance with active bacterial-level infection or colonization arising from endogenous pleomorphic development rather than external infection.",
    diagnosticCriteria: "Dark field microscopy shows elongated, rod-shaped forms with distinct cell boundaries. They demonstrate active motility. Distinguished from exogenous bacteria by their developmental context within the cyclogeny and associated pleomorphic forms at various stages.",
    differentialDiagnosis: "Exogenous bacterial infection, fibrin fragments, cellular debris",
    magnification: "1000x",
    stainType: "dark_field",
    sampleType: "whole blood",
    morphologyDescription: "Elongated rod-shaped forms with smooth boundaries. May appear as short rods (coccobacilli) or longer bacillary forms. Active motility in dark field. May occur alongside earlier cyclogeny forms (protits, chondrites) suggesting developmental progression.",
    sizeRange: "1-5 micrometers length, 0.5-1 micrometer width",
    shapeCharacteristics: "Elongated rods, straight or slightly curved",
    colorCharacteristics: "Bright rods against dark field background",
    associatedConditions: ["Active cyclogeny progression", "Bacterial-phase terrain disturbance", "Chronic infection patterns", "Immune compromise"],
    symptoms: ["Active infection symptoms", "Fever", "Inflammation", "Tissue-specific symptoms"],
    transmissionRoute: null,
    prevalence: "Present in significantly disturbed terrain",
    identificationKeywords: ["rod form", "bacterial", "bacillus", "cyclogeny", "pleomorphism", "stabchen"],
    aiPromptContext: "When analyzing for rod forms in cyclogeny context: Look for elongated bacterial-phase rods in dark field alongside other pleomorphic forms. If rod forms appear with protits, chondrites, and other cyclogeny stages, this suggests endogenous pleomorphic development rather than exogenous infection.",
    confidenceFactors: "Rod morphology, associated pleomorphic forms, terrain assessment, clinical context",
    sourceCitation: "Dumrese/Haefeli - Dark Field Microscopy: Pleomorphism",
    sortOrder: 106,
    tags: ["pleomorphism", "cyclogeny", "Enderlein", "dark-field", "rod-form", "bacterial"]
  },
  {
    title: "Spindle Forms (Hose/Fusiform Bodies)",
    scientificName: "Enderlein Husoform",
    commonName: "Spindle forms, Hose forms, Fusiform bodies",
    organismType: "blood_cell_morphology",
    category: "morphology",
    description: "Spindle or hose forms are fusiform (spindle-shaped) bodies that appear in the blood as part of Enderlein's cyclogeny. They are elongated with tapered ends, representing a transitional morphology between bacterial rod forms and more complex developmental stages.",
    clinicalSignificance: "Spindle forms indicate a transitional phase in the cyclogeny between bacterial and higher developmental stages. Their presence suggests the biological terrain supports continued upward development and the immune system has not successfully halted the cyclogeny progression.",
    diagnosticCriteria: "Dark field microscopy reveals elongated, spindle-shaped (tapered at both ends) formations in plasma. They are larger than typical bacterial rods and show a characteristic fusiform shape. May demonstrate slow, directional motility.",
    differentialDiagnosis: "Fibrin strands, cellular fragments, fusiform bacteria (Fusobacterium)",
    magnification: "1000x",
    stainType: "dark_field",
    sampleType: "whole blood",
    morphologyDescription: "Elongated fusiform (spindle-shaped) bodies with tapered ends and wider central region. Bright in dark field with smooth surface contour. Larger and more substantial than bacterial rod forms. May contain internal granulation.",
    sizeRange: "3-10 micrometers length",
    shapeCharacteristics: "Fusiform/spindle with tapered ends",
    colorCharacteristics: "Bright spindle shapes in dark field",
    associatedConditions: ["Transitional cyclogeny phase", "Terrain deterioration", "Pre-fungal development stage"],
    symptoms: ["Chronic illness progression", "Treatment resistance", "Systemic inflammation"],
    transmissionRoute: null,
    prevalence: "Uncommon, seen in advanced terrain disturbance",
    identificationKeywords: ["spindle", "hose", "fusiform", "cyclogeny", "pleomorphism", "Enderlein"],
    aiPromptContext: "When analyzing for spindle/hose forms: Look for fusiform bodies with tapered ends in dark field. These represent transitional cyclogeny stages between bacterial and fungal phases. Their presence warrants comprehensive terrain correction protocols.",
    confidenceFactors: "Fusiform morphology, dark field characteristics, cyclogeny context",
    sourceCitation: "Dumrese/Haefeli - Dark Field Microscopy: Pleomorphism",
    sortOrder: 107,
    tags: ["pleomorphism", "cyclogeny", "Enderlein", "dark-field", "spindle", "fusiform"]
  },
  {
    title: "Blood Crystals and Pseudocrystals",
    scientificName: null,
    commonName: "Blood crystals, Pseudocrystals, Crystalline formations",
    organismType: "crystal",
    category: "morphology",
    description: "Crystals and pseudocrystals in blood are crystalline formations visible under dark field and phase contrast microscopy. They indicate metabolic disturbance, terrain imbalance, or toxic accumulation. According to Dumrese/Haefeli, these formations are significant markers of internal terrain dysfunction.",
    clinicalSignificance: "Crystalline formations in blood indicate metabolic waste accumulation, pH imbalance, or specific metabolic disorders. Different crystal morphologies correlate with different underlying conditions: needle-shaped (uric acid), plate-like (cholesterol), irregular (metabolic waste). They reflect the body's inability to properly process and eliminate metabolic byproducts.",
    diagnosticCriteria: "Dark field or phase contrast microscopy reveals crystalline structures in plasma or associated with cell surfaces. Crystal shape, size, and distribution pattern help identify the underlying cause. May be static or slowly developing during observation.",
    differentialDiagnosis: "Uric acid crystals, cholesterol crystals, calcium oxalate, drug crystals, cryoglobulins",
    magnification: "400-1000x",
    stainType: "dark_field",
    sampleType: "whole blood",
    morphologyDescription: "Variable crystalline structures: needle-shaped (uric acid), rhomboid plates (cholesterol), irregular geometric forms (metabolic waste), pseudocrystalline aggregates (protein-mineral complexes). Bright, angular, and refractile in dark field with sharp edges and geometric boundaries.",
    sizeRange: "5-50 micrometers",
    shapeCharacteristics: "Geometric: needles, plates, rhomboids, irregular polyhedra",
    colorCharacteristics: "Highly refractile and bright in dark field, may show birefringence",
    associatedConditions: ["Metabolic disturbance", "Gout", "Hyperlipidemia", "Kidney stress", "Acidosis", "Terrain imbalance", "Toxic accumulation"],
    symptoms: ["Joint pain (uric acid)", "Cardiovascular symptoms (cholesterol)", "Kidney symptoms", "Generalized toxicity signs"],
    transmissionRoute: null,
    prevalence: "Common in metabolically compromised individuals",
    identificationKeywords: ["crystal", "pseudocrystal", "uric acid", "cholesterol", "metabolic", "terrain"],
    aiPromptContext: "When analyzing for blood crystals: Identify crystal morphology to determine type. Needle-shaped suggests uric acid/gout. Plate-like suggests cholesterol. Irregular geometric forms suggest general metabolic waste. Correlate with terrain assessment (pH, mineral balance) and patient symptoms.",
    confidenceFactors: "Crystal morphology, clinical symptoms, terrain markers, dietary history",
    sourceCitation: "Dumrese/Haefeli - Dark Field Microscopy: Pleomorphism",
    isFeatured: true,
    sortOrder: 108,
    tags: ["crystal", "pseudocrystal", "metabolic", "dark-field", "terrain", "gout"]
  },
  {
    title: "Mucor Racemosus Endobiont (Symbiont Phase)",
    scientificName: "Mucor racemosus Fresen",
    commonName: "Mucor endobiont, Blood symbiont",
    organismType: "fungus",
    category: "morphology",
    description: "According to Enderlein's theory, Mucor racemosus exists as an endobiont (internal symbiont) in all human blood. In its lower developmental forms (protit and bacterial phases), it participates in normal physiological processes including blood coagulation regulation. Upward development toward fungal forms indicates terrain disturbance.",
    clinicalSignificance: "The Mucor racemosus endobiont cycle is central to Enderlein's understanding of blood physiology. In symbiotic phase, it aids coagulation regulation. In parasitic and fungal phases, it contributes to thrombotic tendencies, circulatory disturbances, and chronic disease. Isopathic remedies (Mucokehl) aim to restore symbiotic balance.",
    diagnosticCriteria: "Dark field microscopy at various magnifications reveals different developmental stages: protit phase (tiny motile particles), bacterial phase (short rods), transitional forms (filaments), and fungal phase (branching hyphae). The stage observed indicates terrain status.",
    differentialDiagnosis: "Other fungal organisms, fibrin formations, cellular debris",
    magnification: "1000x",
    stainType: "dark_field",
    sampleType: "whole blood",
    morphologyDescription: "Varies by developmental stage. Symbiont phase: tiny protit particles and small rod forms. Parasitic phase: larger rods, filaments, and transitional forms. Fungal phase: branching hyphae with characteristic Mucor morphology including sporangia-like structures.",
    sizeRange: "0.01 micrometers (protit) to 20+ micrometers (fungal)",
    shapeCharacteristics: "Stage-dependent: points, rods, filaments, branching hyphae",
    colorCharacteristics: "Bright in dark field, intensity increases with developmental stage",
    associatedConditions: ["Thrombotic tendencies (parasitic phase)", "Circulatory disturbances", "Chronic fatigue", "Coagulation disorders", "Atherosclerosis tendencies"],
    symptoms: ["Circulatory problems", "Cold extremities", "Thrombotic events", "Chronic fatigue", "Varicose veins"],
    transmissionRoute: null,
    prevalence: "Universal endobiont per Enderlein - stage determines pathology",
    identificationKeywords: ["Mucor", "racemosus", "endobiont", "symbiont", "Enderlein", "cyclogeny", "Mucokehl"],
    aiPromptContext: "When analyzing for Mucor racemosus endobiont: Assess developmental stage visible in dark field. Symbiont phase (protits, small rods) is normal. Parasitic phase (larger forms, filaments) indicates terrain disturbance. Fungal phase (branching hyphae) indicates severe disturbance. Isopathic therapy with Mucokehl aims to restore symbiotic phase.",
    confidenceFactors: "Developmental stage assessment, terrain markers, clinical presentation, response to isopathic therapy",
    sourceCitation: "Dumrese/Haefeli - Dark Field Microscopy: Pleomorphism, Chapter VI Blood Mycology",
    isFeatured: true,
    sortOrder: 110,
    tags: ["Mucor", "endobiont", "symbiont", "cyclogeny", "Enderlein", "pleomorphism", "mycology"]
  },
  {
    title: "Aspergillus Niger Endobiont",
    scientificName: "Aspergillus niger van Tieghem",
    commonName: "Aspergillus endobiont",
    organismType: "fungus",
    category: "morphology",
    description: "According to Enderlein, Aspergillus niger exists as a second major endobiont in human blood alongside Mucor racemosus. In its lower developmental forms, it participates in normal calcium and mineral metabolism. Upward development toward fungal forms correlates with tuberculinic terrain and skeletal/connite tissue disorders.",
    clinicalSignificance: "The Aspergillus niger endobiont cycle relates to mineral metabolism, particularly calcium. In symbiotic phase, it supports normal mineral handling. In parasitic and fungal phases, it contributes to calcium deposition disorders, joint problems, skeletal issues, and tuberculinic tendencies. Isopathic remedies (Nigersan) aim to restore balance.",
    diagnosticCriteria: "Dark field microscopy reveals developmental forms distinct from Mucor cycle. Aspergillus cycle forms tend to be more angular and structured. Higher developmental forms show characteristic septate hyphae and conidiophore-like structures.",
    differentialDiagnosis: "Mucor racemosus cycle forms, other fungal organisms",
    magnification: "1000x",
    stainType: "dark_field",
    sampleType: "whole blood",
    morphologyDescription: "Developmental stages from protit phase through bacterial phase to fungal phase. Aspergillus cycle forms are more angular than Mucor forms. Fungal phase shows septate hyphae and characteristic conidiophore structures with chains of conidia.",
    sizeRange: "0.01 micrometers (protit) to 30+ micrometers (fungal)",
    shapeCharacteristics: "Stage-dependent: angular protits, structured rods, septate hyphae",
    colorCharacteristics: "Bright with angular definition in dark field",
    associatedConditions: ["Calcium metabolism disorders", "Joint problems", "Skeletal disorders", "Tuberculinic tendencies", "Connective tissue disorders"],
    symptoms: ["Joint pain", "Skeletal issues", "Calcium deposits", "Connective tissue problems", "Chronic respiratory issues"],
    transmissionRoute: null,
    prevalence: "Universal endobiont per Enderlein - stage determines pathology",
    identificationKeywords: ["Aspergillus", "niger", "endobiont", "Nigersan", "Enderlein", "cyclogeny", "tuberculinic"],
    aiPromptContext: "When analyzing for Aspergillus niger endobiont: Look for angular, structured developmental forms distinct from the Mucor cycle. Higher forms show septate hyphae. Correlates with calcium/mineral metabolism and tuberculinic terrain. Isopathic therapy with Nigersan aims to restore symbiotic phase.",
    confidenceFactors: "Angular morphology, developmental stage, calcium metabolism markers, tuberculinic tendencies",
    sourceCitation: "Dumrese/Haefeli - Dark Field Microscopy: Pleomorphism, Chapter VI Blood Mycology",
    sortOrder: 111,
    tags: ["Aspergillus", "endobiont", "symbiont", "cyclogeny", "Enderlein", "tuberculinic", "mycology"]
  },
  {
    title: "Dry Layer Oxidative Stress Pattern - Normal",
    scientificName: null,
    commonName: "Normal dry layer, Healthy oxidative stress test",
    organismType: "blood_cell_morphology",
    category: "reference_normal",
    description: "A normal dry layer oxidative stress test (Bradford/HLB test) shows healthy blood that has dried with uniform fibrin polymerization creating a tight, interconnected mesh pattern across all layers of the dried blood drop. This represents healthy coagulation cascade function and minimal oxidative burden.",
    clinicalSignificance: "Normal dry layer patterns indicate healthy fibrin polymerization, minimal oxidative stress, and proper coagulation cascade function. The tight mesh pattern reflects adequate antioxidant reserves, healthy liver function, and proper protein synthesis. This serves as the baseline reference for evaluating pathological dry layer patterns.",
    diagnosticCriteria: "Dried blood drop shows uniform, tight interconnected fibrin mesh across all 8 layers (counted from center to periphery). No clear lacunae (holes), no dark spots, no pattern disruptions. Consistent polymerization throughout the drop.",
    differentialDiagnosis: "Early oxidative stress (may still appear near-normal)",
    magnification: "40-100x",
    stainType: "unstained",
    sampleType: "dried blood drop",
    morphologyDescription: "Uniform, tight interconnected mesh of polymerized fibrin across all layers of the dried blood drop. The mesh is consistent from center to periphery. No clear holes, no dark accumulations, no disrupted zones. The overall appearance is of a finely woven, uniform fabric.",
    sizeRange: "Dried drop 6-8mm diameter",
    shapeCharacteristics: "Uniform mesh pattern, consistent density",
    colorCharacteristics: "Uniform dark red-brown mesh on white background",
    associatedConditions: ["Healthy antioxidant status", "Normal coagulation", "Adequate liver function"],
    symptoms: ["None - reference normal"],
    transmissionRoute: null,
    prevalence: "Seen in healthy individuals with good antioxidant status",
    identificationKeywords: ["dry layer", "oxidative stress test", "Bradford", "HLB", "normal", "fibrin polymerization"],
    aiPromptContext: "Reference for normal dry layer: Uniform, tight fibrin mesh across all layers with no lacunae, dark spots, or disruptions. Use as baseline when evaluating pathological patterns. Any deviation from uniform mesh indicates oxidative stress or specific organ burden.",
    confidenceFactors: "Consistent mesh pattern, no disruptions, clinical correlation",
    sourceCitation: "Biomedx Microscope Training Program - Day 3 Curriculum",
    sortOrder: 120,
    tags: ["dry-layer", "oxidative-stress", "Bradford", "HLB", "reference", "normal"]
  },
  {
    title: "Dry Layer Oxidative Stress Pattern - Lacunae",
    scientificName: null,
    commonName: "Oxidative stress holes, Clear lacunae pattern",
    organismType: "blood_cell_morphology",
    category: "oxidative_stress",
    description: "Clear lacunae (holes) in the dry layer oxidative stress test indicate disrupted fibrin polymerization caused by free radical damage. The size, number, and distribution of lacunae across the dried blood drop layers correlate with the degree and location of oxidative stress in the body.",
    clinicalSignificance: "Lacunae in the dry layer test indicate that free radicals have disrupted the fibrin polymerization cascade during drying. Larger and more numerous lacunae indicate greater oxidative burden. The location within the dried drop (which of the 8 layers) correlates with specific organ systems under oxidative stress according to the Biomedx mapping system.",
    diagnosticCriteria: "Dried blood drop shows clear, white lacunae (holes) in the otherwise dark fibrin mesh. Graded by number, size, and layer distribution. Mild: small, few lacunae in outer layers. Moderate: medium lacunae in multiple layers. Severe: large, confluent lacunae throughout.",
    differentialDiagnosis: "Air bubbles (artifact), sample preparation errors",
    magnification: "40-100x",
    stainType: "unstained",
    sampleType: "dried blood drop",
    morphologyDescription: "Clear white holes of variable size within the dark polymerized fibrin mesh. Holes have irregular to rounded edges. They may be isolated or confluent. Distribution across the 8 concentric layers of the dried drop follows organ-system mapping patterns.",
    sizeRange: "0.1-3mm lacunae within 6-8mm dried drop",
    shapeCharacteristics: "Irregular to rounded holes in fibrin mesh",
    colorCharacteristics: "White/clear holes in dark red-brown mesh",
    associatedConditions: ["Oxidative stress", "Free radical damage", "Antioxidant deficiency", "Chronic inflammation", "Degenerative conditions"],
    symptoms: ["Fatigue", "Accelerated aging", "Chronic pain", "Cognitive decline", "Multiple system symptoms depending on affected layers"],
    transmissionRoute: null,
    prevalence: "Very common in modern populations with oxidative burden",
    identificationKeywords: ["lacunae", "oxidative stress", "dry layer", "holes", "fibrin disruption", "free radical"],
    aiPromptContext: "When analyzing dry layer lacunae: Count, measure, and map lacunae to the 8-layer system. Center layers (1-2): cardiovascular/respiratory. Middle layers (3-5): digestive/hepatic/renal. Outer layers (6-8): immune/hormonal/musculoskeletal. Larger and more numerous lacunae = greater oxidative burden in mapped organ systems.",
    confidenceFactors: "Consistent lacunae pattern, multiple drops showing same pattern, clinical correlation, antioxidant status testing",
    sourceCitation: "Biomedx Microscope Training Program - Day 3 Curriculum",
    isFeatured: true,
    sortOrder: 121,
    tags: ["dry-layer", "oxidative-stress", "lacunae", "free-radical", "fibrin", "antioxidant"]
  },
  {
    title: "Dry Layer - Heavy Metal Toxicity Pattern",
    scientificName: null,
    commonName: "Heavy metal dark spots, Toxic metal pattern",
    organismType: "blood_cell_morphology",
    category: "oxidative_stress",
    description: "Dark spots or dense accumulations in the dry layer test are associated with heavy metal toxicity. These concentrated dark areas within the dried blood drop represent areas where metals have disrupted normal fibrin polymerization and created localized areas of protein denaturation.",
    clinicalSignificance: "Dark spots in the dry layer pattern correlate with heavy metal burden. Their location within the dried blood drop layers may indicate which organ systems are most affected by metal accumulation. Combined with other testing (hair mineral analysis, blood metals), this provides a visual indicator of toxic metal burden.",
    diagnosticCriteria: "Dried blood drop shows concentrated dark spots or dense accumulations within the fibrin mesh. These are darker than surrounding polymerized fibrin. May appear as solid dark areas, dense granular accumulations, or dark streaks.",
    differentialDiagnosis: "Blood clots, hemoglobin concentration artifacts, pigmented debris",
    magnification: "40-100x",
    stainType: "unstained",
    sampleType: "dried blood drop",
    morphologyDescription: "Concentrated dark spots or dense granular accumulations within the fibrin mesh. Darker than surrounding polymerized fibrin. May be focal or diffuse. Often appear in specific layer zones correlating with organs of metal accumulation (liver, kidney, brain).",
    sizeRange: "0.5-2mm dark areas within dried drop",
    shapeCharacteristics: "Dense dark focal or diffuse areas",
    colorCharacteristics: "Very dark brown to black against the red-brown fibrin mesh",
    associatedConditions: ["Heavy metal toxicity", "Lead exposure", "Mercury burden", "Arsenic exposure", "Cadmium accumulation"],
    symptoms: ["Neurological symptoms", "Cognitive dysfunction", "Kidney issues", "Liver burden", "Chronic fatigue", "Neuropathy"],
    transmissionRoute: null,
    prevalence: "Common in environmentally exposed populations",
    identificationKeywords: ["heavy metal", "dark spots", "dry layer", "toxicity", "lead", "mercury", "metal burden"],
    aiPromptContext: "When analyzing dry layer dark spots: Dark concentrated areas suggest heavy metal accumulation. Map location to organ systems. Confirm with hair mineral analysis, blood metal panels. Consider chelation or detoxification protocols. These patterns often coexist with oxidative stress lacunae.",
    confidenceFactors: "Consistent dark spot pattern, confirmatory metal testing, exposure history, clinical symptoms",
    sourceCitation: "Biomedx Microscope Training Program - Day 3 Curriculum",
    sortOrder: 122,
    tags: ["dry-layer", "heavy-metal", "toxicity", "dark-spots", "oxidative-stress"]
  },
  {
    title: "Zeta Potential Disruption (RBC Aggregation Pattern)",
    scientificName: null,
    commonName: "Zeta potential loss, RBC sludging, Blood viscosity",
    organismType: "blood_cell_morphology",
    category: "coagulation",
    description: "Zeta potential disruption is observed when red blood cells lose their normal negative surface charge, leading to aggregation, rouleaux formation, and blood sludging. In dark field microscopy, this appears as progressive RBC stacking and clumping beyond normal levels, indicating compromised colloidal suspension of blood.",
    clinicalSignificance: "Reduced zeta potential compromises blood's ability to maintain cells in free-flowing colloidal suspension. This leads to impaired microcirculation, reduced oxygen delivery, increased blood viscosity, and cardiovascular risk. Causes include: dehydration, acidosis, excess cationic minerals (aluminum, excess iron), inflammatory proteins, and acidic terrain.",
    diagnosticCriteria: "Dark field microscopy shows progressive RBC aggregation beyond mild rouleaux: moderate to severe stacking, 3D clumping, blood appearing 'sludged.' Free-flowing individual RBCs are rare. Plasma may appear cloudy with debris. Distinguished from simple rouleaux by severity and distribution.",
    differentialDiagnosis: "Simple dehydration-related rouleaux, paraproteinemia, sample aging artifact",
    magnification: "400-1000x",
    stainType: "dark_field",
    sampleType: "whole blood",
    morphologyDescription: "Severe RBC aggregation with large stacks (>10 cells), 3D clumping, and minimal free-flowing individual cells. Plasma may contain visible debris and microforms. Overall blood appearance is sludged rather than free-flowing. RBC membranes may show reduced clarity suggesting surface charge loss.",
    sizeRange: "Normal RBC size but in aggregates of 10-50+ cells",
    shapeCharacteristics: "Stacked and clumped aggregates, loss of individual cell dispersion",
    colorCharacteristics: "Dense, overlapping bright discs forming thick stacks in dark field",
    associatedConditions: ["Cardiovascular risk", "Poor microcirculation", "Dehydration", "Chronic inflammation", "Acidosis", "Aluminum/heavy metal exposure"],
    symptoms: ["Cold extremities", "Poor wound healing", "Cognitive fog", "Fatigue", "Hypertension", "Peripheral neuropathy"],
    transmissionRoute: null,
    prevalence: "Common in dehydrated and chronically ill populations",
    identificationKeywords: ["zeta potential", "aggregation", "sludging", "viscosity", "rouleaux", "colloidal"],
    aiPromptContext: "When analyzing for zeta potential disruption: Assess severity of RBC aggregation beyond normal rouleaux. Grade 1: mild stacking (3-5 cells). Grade 2: moderate stacking (6-10 cells). Grade 3: severe sludging (>10 cells, 3D clumps). Grade 4: near-complete aggregation. Correlate with hydration status, cationic mineral load, pH, and inflammatory markers.",
    confidenceFactors: "Aggregation severity, correlation with hydration status, terrain assessment, response to hydration challenge",
    sourceCitation: "Biomedx Microscope Training Program; Blood Colloid Science",
    isFeatured: true,
    sortOrder: 130,
    tags: ["zeta-potential", "aggregation", "viscosity", "colloidal", "microcirculation", "terrain"]
  },
  {
    title: "Fibrin Polymerization Disruption (Coagulation Cascade Marker)",
    scientificName: null,
    commonName: "Fibrin spicules, Fibrin networks, Coagulation marker",
    organismType: "protein_pattern",
    category: "coagulation",
    description: "Fibrin polymerization disruptions visible in both live and dried blood analysis indicate abnormalities in the coagulation cascade. In live blood, excessive fibrin strands, spicules, and networks suggest liver stress and inflammatory activation. In dried blood, disrupted fibrin mesh patterns reveal oxidative stress and coagulation cascade dysfunction.",
    clinicalSignificance: "Excessive fibrin activity in live blood indicates activation of the coagulation cascade, often due to liver stress (fibrinogen production), inflammation (thrombin activation), or oxidative damage to coagulation proteins. This represents cardiovascular risk and systemic inflammatory burden. Combined with dry layer assessment, provides comprehensive coagulation health picture.",
    diagnosticCriteria: "Live blood dark field: excessive fibrin strands, spicules projecting from cell surfaces, fibrin networks entrapping cells. Dried blood: disrupted polymerization patterns with irregular mesh density, holes, and pattern breaks. Grade by severity of fibrin activity.",
    differentialDiagnosis: "Normal minimal fibrin activity, sample aging artifact, anticoagulant contamination",
    magnification: "400-1000x",
    stainType: "dark_field",
    sampleType: "whole blood",
    morphologyDescription: "Live blood: bright, thread-like strands radiating from cell surfaces or forming networks in plasma. May range from subtle spicules to extensive networks entrapping multiple cells. Dried blood: irregular mesh patterns with variable density, broken fibers, and structural disruptions.",
    sizeRange: "Spicules 1-10 micrometers, networks variable",
    shapeCharacteristics: "Thread-like strands, radiating spicules, web-like networks",
    colorCharacteristics: "Bright white strands and networks in dark field",
    associatedConditions: ["Liver stress", "Chronic inflammation", "Cardiovascular risk", "Oxidative stress", "Coagulation cascade activation", "Fibrinolysis imbalance"],
    symptoms: ["Easy bruising", "Clotting tendency", "Cardiovascular symptoms", "Liver symptoms", "Chronic inflammation signs"],
    transmissionRoute: null,
    prevalence: "Common finding in inflammatory and liver-stressed individuals",
    identificationKeywords: ["fibrin", "spicules", "coagulation", "polymerization", "liver stress", "inflammation"],
    aiPromptContext: "When analyzing fibrin activity: Grade severity. Mild: occasional spicules. Moderate: multiple strands and small networks. Severe: extensive networks entrapping cells. Correlate with liver function markers, inflammatory markers, and cardiovascular risk assessment. In dry layer, map disrupted polymerization to organ system layers.",
    confidenceFactors: "Fibrin severity grade, liver function correlation, inflammatory marker correlation, fresh sample confirmed",
    sourceCitation: "Biomedx Microscope Training; Dumrese/Haefeli - Dark Field Microscopy",
    sortOrder: 131,
    tags: ["fibrin", "coagulation", "liver-stress", "inflammation", "cardiovascular", "polymerization"]
  }
];

export async function seedLBABloodSamples(): Promise<void> {
  console.log("Starting LBA/pleomorphic blood sample library seeding...");
  
  for (const sampleData of lbaBloodSampleData) {
    try {
      const { tags, ...sample } = sampleData;

      const existing = await db.select({ id: bloodSamples.id })
        .from(bloodSamples)
        .where(eq(bloodSamples.title, sample.title))
        .limit(1);

      if (existing.length > 0) {
        console.log(`Sample already exists, skipping: ${sampleData.title}`);
        continue;
      }
      
      const createdSample = await storage.createBloodSample(sample);
      console.log(`Created LBA blood sample: ${createdSample.title}`);
      
      for (const tag of tags) {
        await storage.addBloodSampleTag({
          sampleId: createdSample.id,
          tag: tag,
          tagCategory: null
        });
      }
      console.log(`  Added ${tags.length} tags`);
      
    } catch (error: any) {
      if (error.code === '23505') {
        console.log(`Sample already exists: ${sampleData.title}`);
      } else {
        console.error(`Error creating sample ${sampleData.title}:`, error.message);
      }
    }
  }
  
  console.log("LBA/pleomorphic blood sample library seeding complete!");
}
